'use client';

import { useEffect, useState } from 'react';
import { RefreshCw, Save, PackageCheck, AlertTriangle, ShoppingBag, Users, IndianRupee, Boxes, Search, LogOut } from 'lucide-react';
import { createClient } from '@/lib/supabase-browser';

const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

export default function WebsitePage(){
  const [tab,setTab]=useState('dashboard'); const [data,setData]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [settings,setSettings]=useState(null); const [saving,setSaving]=useState(false); const [products,setProducts]=useState([]); const [transactions,setTransactions]=useState([]); const [orders,setOrders]=useState([]); const [customers,setCustomers]=useState([]); const [selected,setSelected]=useState(''); const [change,setChange]=useState(''); const [reason,setReason]=useState(''); const [msg,setMsg]=useState('');
  const load=async(t=tab)=>{setLoading(true);setError('');setMsg('');try{const r=await fetch(`/api/website/${t}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load'); if(t==='dashboard')setData(j); if(t==='settings')setSettings(j.data||{}); if(t==='inventory'){setProducts(j.products||[]);setTransactions(j.transactions||[])} if(t==='orders')setOrders(j.data||[]); if(t==='customers')setCustomers(j.data||[]);}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load(tab)},[tab]);
  const logout=async()=>{await createClient().auth.signOut();location.href='/login'};
  const adjust=async e=>{e.preventDefault();setError('');const r=await fetch('/api/website/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:selected,change_quantity:Number(change),reason})});const j=await r.json();if(!r.ok)setError(j.error);else{setMsg('Stock adjusted.');setChange('');setReason('');load('inventory')}};
  const save=async e=>{e.preventDefault();setSaving(true);setError('');const r=await fetch('/api/website/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const j=await r.json();if(!r.ok)setError(j.error);else{setSettings(j.data);setMsg('Website settings saved.')}setSaving(false)};
  const changeOrder=async(o,status)=>{const r=await fetch('/api/website/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:o.id,order_status:status,status_note:`Status changed to ${status}`})});const j=await r.json();if(!r.ok)setError(j.error);else load('orders')};
  const filtered=customers.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));
  const nav=[['dashboard','Dashboard'],['orders','Orders'],['inventory','Inventory'],['customers','Customers'],['settings','Settings']];
  return <div className="min-h-screen bg-gray-50 text-gray-900"><header className="sticky top-0 z-10 border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3"><div><div className="text-xl font-bold">PinkBox</div><div className="text-xs text-gray-500">Website Admin</div></div><button onClick={logout} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><LogOut size={16}/>Logout</button></div></header><div className="mx-auto flex max-w-7xl flex-col gap-5 p-4 md:flex-row"><aside className="w-full rounded-2xl border bg-white p-2 md:w-52 md:h-fit">{nav.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`mb-1 w-full rounded-xl px-3 py-2.5 text-left text-sm font-medium ${tab===id?'bg-gray-900 text-white':'hover:bg-gray-100'}`}>{label}</button>)}</aside><main className="min-w-0 flex-1">{(error||msg)&&<div className={`mb-4 rounded-xl p-4 text-sm ${error?'bg-red-50 text-red-700':'bg-green-50 text-green-700'}`}>{error||msg}</div>}{loading&&tab!=='settings'?<div className="rounded-2xl border bg-white p-12 text-center text-gray-500">Loading…</div>:tab==='dashboard'&&data?<Dashboard d={data}/>:tab==='orders'?<Orders rows={orders} change={changeOrder}/>:tab==='inventory'?<Inventory products={products} transactions={transactions} selected={selected} setSelected={setSelected} change={change} setChange={setChange} reason={reason} setReason={setReason} adjust={adjust}/>:tab==='customers'?<Customers rows={filtered} query={query} setQuery={setQuery}/>:tab==='settings'&&settings?<Settings s={settings} setS={setSettings} save={save} saving={saving}/>:<div/>}</main></div></div>
}
function Dashboard({d}){return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Website Dashboard</h1><p className="mt-1 text-sm text-gray-500">24Care online store overview.</p></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={IndianRupee} label="Sales" value={money(d.stats.sales)}/><Card icon={ShoppingBag} label="Orders" value={d.stats.orders}/><Card icon={PackageCheck} label="Products" value={d.stats.products}/><Card icon={Users} label="Customers" value={d.stats.customers}/></div><div className="grid gap-5 xl:grid-cols-2"><Box title="Recent Orders">{d.recentOrders.length?d.recentOrders.map(o=><div key={o.id} className="flex justify-between border-b px-5 py-4"><div><b>{o.order_number||o.id.slice(0,8)}</b><div className="text-xs text-gray-500">{new Date(o.created_at).toLocaleString('en-IN')}</div></div><div className="text-right"><b>{money(o.total_amount)}</b><div className="text-xs uppercase text-gray-500">{o.order_status}</div></div></div>):<Empty/>}</Box><Box title="Low Stock">{d.lowStock.length?d.lowStock.map(p=><div key={p.id} className="flex justify-between border-b px-5 py-4"><div><b>{p.title}</b><div className="text-xs text-gray-500">{p.sku}</div></div><b className="text-amber-600">{p.stock_quantity||0}</b></div>):<Empty/>}</Box></div></div>}
const Card=({icon:Icon,label,value})=><div className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3 text-gray-500"><Icon size={18}/><span className="text-sm">{label}</span></div><div className="mt-3 text-2xl font-semibold">{value}</div></div>;
const Box=({title,children})=><div className="overflow-hidden rounded-2xl border bg-white"><div className="border-b px-5 py-4 font-semibold">{title}</div>{children}</div>;
const Empty=()=> <div className="p-8 text-center text-sm text-gray-500">No records yet.</div>;
function Orders({rows,change}){const statuses=['new','confirmed','processing','packed','shipped','delivered','cancelled','returned','refunded'];return <Box title="Orders"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Order</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Date</th></tr></thead><tbody className="divide-y">{rows.length?rows.map(o=><tr key={o.id}><td className="px-4 py-3 font-medium">{o.order_number}</td><td className="px-4 py-3">{o.customer_name||'—'}<div className="text-xs text-gray-500">{o.phone||o.email||''}</div></td><td className="px-4 py-3">{money(o.total_amount)}</td><td className="px-4 py-3">{o.payment_method} / {o.payment_status}</td><td className="px-4 py-3"><select value={o.order_status} onChange={e=>change(o,e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs">{statuses.map(x=><option key={x}>{x}</option>)}</select></td><td className="px-4 py-3">{new Date(o.created_at).toLocaleDateString('en-IN')}</td></tr>):<tr><td colSpan="6"><Empty/></td></tr>}</tbody></table></div></Box>}
function Inventory({products,transactions,selected,setSelected,change,setChange,reason,setReason,adjust}){return <div className="space-y-5"><Box title="Stock Overview">{products.map(p=><div key={p.id} className="flex justify-between border-b px-5 py-4"><div><b>{p.title}</b><div className="text-xs text-gray-500">{p.sku}</div></div><div className="text-right"><b>{p.stock_quantity||0}</b><div className="text-xs text-gray-400">alert {p.low_stock_threshold||0}</div></div></div>)}{!products.length&&<Empty/>}</Box><form onSubmit={adjust} className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center gap-2 font-semibold"><Boxes size={18}/>Stock Adjustment</div><select required value={selected} onChange={e=>setSelected(e.target.value)} className="mb-3 w-full rounded-xl border px-3 py-2.5"><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.title} ({p.sku})</option>)}</select><input required type="number" value={change} onChange={e=>setChange(e.target.value)} placeholder="+10 or -5" className="mb-3 w-full rounded-xl border px-3 py-2.5"/><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason" rows="3" className="mb-3 w-full rounded-xl border px-3 py-2.5"/><button className="w-full rounded-xl bg-gray-900 py-2.5 font-semibold text-white">Adjust Stock</button></form><Box title="Recent Stock Transactions">{transactions.length?transactions.map(t=><div key={t.id} className="flex justify-between border-b px-5 py-3 text-sm"><span>{t.reason||'Adjustment'}</span><span>{t.change_quantity} · {t.quantity_after}</span></div>):<Empty/>}</Box></div>}
function Customers({rows,query,setQuery}){return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">Customers</h1><p className="text-sm text-gray-500">Live customer master from BK CRM.</p></div><div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customers..." className="w-full rounded-xl border bg-white py-2.5 pl-10 pr-3"/></div><Box title="Customer Master"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Firm</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">GSTIN</th></tr></thead><tbody className="divide-y">{rows.map(x=><tr key={x.id}><td className="px-4 py-3 font-medium">{[x.client_name,x.surname].filter(Boolean).join(' ')||'—'}</td><td className="px-4 py-3">{x.firm_name||'—'}</td><td className="px-4 py-3">{x.phone1||x.phone2||'—'}</td><td className="px-4 py-3">{x.email||'—'}</td><td className="px-4 py-3">{[x.city,x.state,x.pincode].filter(Boolean).join(', ')||'—'}</td><td className="px-4 py-3">{x.gstin||'—'}</td></tr>)}</tbody></table></div></Box></div>}
function Settings({s,setS,save,saving}){const fields=[['website_name','Website Name'],['slug','Slug'],['logo_url','Logo URL'],['favicon_url','Favicon URL'],['whatsapp_number','WhatsApp Number'],['phone','Phone'],['email','Email'],['gstin','GSTIN'],['currency','Currency'],['timezone','Timezone'],['address','Business Address'],['meta_title','Meta Title'],['meta_description','Meta Description'],['free_shipping_threshold','Free Shipping Threshold'],['default_shipping_charge','Default Shipping Charge']];return <form onSubmit={save} className="space-y-5"><div><h1 className="text-2xl font-semibold">Website Settings</h1><p className="mt-1 text-sm text-gray-500">24Care storefront identity, contact, commerce and SEO defaults.</p></div><div className="grid gap-5 rounded-2xl border bg-white p-5 lg:grid-cols-2">{fields.map(([k,l])=><label key={k} className={['address','meta_description'].includes(k)?'lg:col-span-2':''}><span className="mb-1.5 block text-sm font-medium">{l}</span>{['address','meta_description'].includes(k)?<textarea rows={3} value={s[k]??''} onChange={e=>setS({...s,[k]:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/>:<input type={k.includes('threshold')||k.includes('charge')?'number':'text'} value={s[k]??''} onChange={e=>setS({...s,[k]:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/>}</label>)}</div><div className="flex flex-wrap gap-5 rounded-2xl border bg-white p-5">{[['cod_enabled','Cash on Delivery'],['online_payment_enabled','Online Payment'],['shipping_enabled','Shipping']].map(([k,l])=><label key={k} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!s[k]} onChange={e=>setS({...s,[k]:e.target.checked})}/>{l}</label>)}</div><button disabled={saving} className="rounded-xl bg-gray-900 px-5 py-3 font-semibold text-white">{saving?'Saving…':'Save Settings'}</button></form>}
