'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,ShoppingBag,Menu,X,Plus,Minus,Truck,ShieldCheck,Loader2,PackageCheck} from 'lucide-react';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const read=async r=>{const t=await r.text();let j;try{j=JSON.parse(t)}catch{throw Error(`Request failed (${r.status})`)}if(!r.ok)throw Error(j.error||'Request failed');return j};
export default function Home(){
 const[d,setD]=useState(null),[q,setQ]=useState(''),[cat,setCat]=useState('all'),[cart,setCart]=useState([]),[view,setView]=useState(null),[drawer,setDrawer]=useState(false),[checkout,setCheckout]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[sid,setSid]=useState(''),[form,setForm]=useState({name:'',phone:'',email:'',address:'',pincode:'',city:'',state:'',note:'',coupon_code:'',payment_method:'cod'});
 useEffect(()=>{let s=localStorage.getItem('pinkbox_session_id');if(!s){s=`pinkbox-${crypto.randomUUID()}`;localStorage.setItem('pinkbox_session_id',s)}setSid(s);try{setCart(JSON.parse(localStorage.getItem('pinkbox_cart')||'[]'))}catch{}fetch('/api/storefront',{cache:'no-store'}).then(read).then(setD).catch(e=>setErr(e.message))},[]);
 useEffect(()=>localStorage.setItem('pinkbox_cart',JSON.stringify(cart)),[cart]);
 const settings=d?.settings||{},primary=d?.theme?.primary_color||'#d9295f',products=d?.products||[],cats=d?.categories||[];
 const filtered=useMemo(()=>products.filter(p=>(cat==='all'||p.category_id===cat)&&(!q||[p.title,p.sku,p.brand,p.short_description,p.description].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase())))),[products,cat,q]);
 const count=cart.reduce((s,x)=>s+x.quantity,0),subtotal=cart.reduce((s,x)=>s+Number(x.price)*x.quantity,0),shipping=settings.shipping_enabled?(subtotal>=Number(settings.free_shipping_threshold||0)&&subtotal?0:Number(settings.default_shipping_charge||0)):0,total=subtotal+shipping;
 const add=p=>{setCart(a=>{const f=a.find(x=>x.id===p.id);return f?a.map(x=>x.id===p.id?{...x,quantity:Math.min(x.quantity+1,Number(p.stock_quantity||999999))}:x):[...a,{...p,quantity:1}]});setView(null);setDrawer(true);setMsg('Added to cart')};
 const change=(id,n)=>setCart(a=>a.map(x=>x.id===id?{...x,quantity:Math.max(0,Math.min(x.quantity+n,Number(x.stock_quantity||999999)))}:x).filter(x=>x.quantity));
 const saveCart=async()=>{if(!sid||!cart.length||(!form.name&&!form.phone))return;try{await fetch('/api/storefront',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'abandoned_cart',session_id:sid,name:form.name,phone:form.phone,email:form.email,items:cart.map(x=>({product_id:x.id,quantity:x.quantity})),subtotal})})}catch{}};
 const order=async e=>{e.preventDefault();setBusy(true);setErr('');try{const j=await read(await fetch('/api/storefront',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,session_id:sid,items:cart.map(x=>({product_id:x.id,quantity:x.quantity}))})}));setMsg(`Order ${j.order_number||j.order_id} placed successfully. Total ${money(j.total_amount||total)}.`);setCart([]);setCheckout(false);setDrawer(false);localStorage.removeItem('pinkbox_cart')}catch(e){setErr(e.message)}finally{setBusy(false)}};
 if(err&&!d)return <main className="grid min-h-screen place-items-center p-6"><div className="rounded-2xl bg-white p-7 text-center shadow"><h1 className="text-xl font-bold">Store unavailable</h1><p className="mt-2 text-sm text-gray-500">{err}</p></div></main>;if(!d)return <main className="grid min-h-screen place-items-center"><Loader2 className="animate-spin"/></main>;
 const hero=d.banners?.[0],pages=d.pages||[],nav=Array.isArray(d.menu?.items)?d.menu.items:[];
 return <div className="min-h-screen bg-white text-slate-900"><div className="bg-slate-950 px-4 py-2 text-center text-xs text-white">{settings.shipping_enabled?'Secure delivery across India':'Welcome to our online store'}</div><header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-4 px-4 py-4"><button className="rounded-xl border p-2 md:hidden" onClick={()=>setDrawer(true)}><Menu size={19}/></button><a href="/" className="flex items-center gap-3">{settings.logo_url?<img src={settings.logo_url} alt={settings.website_name} className="h-10 w-10 rounded-xl object-contain"/>:<div className="grid h-10 w-10 place-items-center rounded-xl text-white font-bold" style={{background:primary}}>PB</div>}<b className="text-xl">{settings.website_name||'PinkBox'}</b></a><nav className="hidden flex-1 justify-center gap-6 md:flex">{nav.length?nav.map((x,i)=><a key={i} href={x.url||x.href||'#products'} className="text-sm font-semibold">{x.label||x.title||x.name}</a>):<><a href="#products" className="text-sm font-semibold">Shop</a><a href="#about" className="text-sm font-semibold">About</a>{pages.slice(0,3).map(p=><a key={p.id} href={`#page-${p.slug}`} className="text-sm font-semibold">{p.title}</a>)}</>}</nav><div className="hidden w-64 items-center rounded-xl border bg-slate-50 px-3 md:flex"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products" className="w-full bg-transparent px-2 py-2.5 text-sm outline-none"/></div><button onClick={()=>setDrawer(true)} className="relative rounded-xl border p-2.5"><ShoppingBag size={19}/>{count>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full px-1 text-[10px] font-bold text-white" style={{background:primary}}>{count}</span>}</button></div></header>
 {hero?<section className="bg-pink-50"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 md:grid-cols-2 md:items-center md:py-20"><div><p className="text-xs font-bold uppercase tracking-[.2em]" style={{color:primary}}>PinkBox</p><h1 className="mt-4 text-5xl font-bold">{hero.title||settings.website_name}</h1><p className="mt-5 max-w-xl text-lg text-slate-600">{hero.subtitle||settings.meta_description||'Shop quality products from PinkBox.'}</p>{hero.button_text&&<a href={hero.button_url||'#products'} className="mt-7 inline-flex rounded-full px-6 py-3.5 font-semibold text-white" style={{background:primary}}>{hero.button_text}</a>}</div><div className="overflow-hidden rounded-[2rem] bg-white">{hero.image_url?<img src={hero.image_url} alt={hero.title||''} className="aspect-[16/10] w-full object-cover"/>:<div className="grid aspect-[16/10] place-items-center text-8xl font-bold" style={{color:primary}}>PB</div>}</div></div></section>:<section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-20"><p className="font-semibold" style={{color:primary}}>WELCOME TO {settings.website_name||'PINKBOX'}</p><h1 className="mt-4 max-w-3xl text-5xl font-bold md:text-7xl">Shop smarter. Delivered better.</h1><p className="mt-5 max-w-2xl text-lg text-white/60">{settings.meta_description||'Discover our latest products and offers.'}</p><a href="#products" className="mt-8 inline-flex rounded-full px-6 py-3.5 font-semibold text-white" style={{background:primary}}>Shop now</a></div></section>}
 <section className="mx-auto max-w-7xl px-4 py-8"><div className="grid gap-3 sm:grid-cols-3"><Benefit I={ShieldCheck} t="Trusted quality" d="Products managed directly by PinkBox."/><Benefit I={Truck} t="Reliable delivery" d="Shipping rules managed in admin."/><Benefit I={PackageCheck} t="Live stock" d="Availability is synced with catalogue."/></div></section>
 <section id="products" className="mx-auto max-w-7xl px-4 py-14"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em]" style={{color:primary}}>Catalogue</p><h2 className="mt-2 text-3xl font-bold">Shop products</h2></div><div className="flex gap-2 overflow-x-auto">{[['all','All'],...cats.map(c=>[c.id,c.name])].map(([id,label])=><button key={id} onClick={()=>setCat(id)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-sm font-semibold ${cat===id?'text-white':''}`} style={cat===id?{background:primary,borderColor:primary}:{}}>{label}</button>)}</div></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map(p=><Card key={p.id} p={p} primary={primary} view={()=>setView(p)} add={()=>add(p)}/>)}</div>{!filtered.length&&<div className="mt-6 rounded-2xl border p-12 text-center text-gray-500">No products found.</div>}</section>
 {d.sections?.map(s=><section key={s.id} className="mx-auto max-w-7xl px-4 py-12"><div className="rounded-3xl bg-slate-950 p-8 text-white"><p className="text-xs uppercase tracking-[.2em]" style={{color:primary}}>{s.section_type}</p><h2 className="mt-3 text-3xl font-bold">{s.title||'Discover more'}</h2><p className="mt-3 text-white/60">{typeof s.settings?.description==='string'?s.settings.description:'This section is controlled from PinkBox Admin.'}</p></div></section>)}
 {d.blog?.length>0&&<section className="mx-auto max-w-7xl px-4 py-14"><h2 className="text-3xl font-bold">Latest from PinkBox</h2><div className="mt-7 grid gap-6 md:grid-cols-3">{d.blog.slice(0,3).map(p=><a key={p.id} href={`/blog/${p.slug}`} className="overflow-hidden rounded-2xl border">{p.cover_image_url&&<img src={p.cover_image_url} alt="" className="aspect-video w-full object-cover"/>}<div className="p-5"><h3 className="text-xl font-semibold">{p.title}</h3><p className="mt-2 text-sm text-slate-500">{p.excerpt||''}</p></div></a>)}</div></section>}
 {pages.map(p=><section id={`page-${p.slug}`} key={p.id} className="mx-auto max-w-5xl px-4 py-12"><h2 className="text-3xl font-bold">{p.title}</h2><div className="mt-4 whitespace-pre-wrap text-slate-600">{typeof p.content?.text==='string'?p.content.text:typeof p.content?.body==='string'?p.content.body:''}</div></section>)}
 <footer id="about" className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 md:grid-cols-3"><div><b className="text-2xl">{settings.website_name||'PinkBox'}</b><p className="mt-3 text-sm text-white/50">{settings.meta_description||'Quality products, simple shopping and reliable delivery.'}</p></div><div><b>Contact</b><div className="mt-3 space-y-2 text-sm text-white/60">{settings.phone&&<div>{settings.phone}</div>}{settings.email&&<div>{settings.email}</div>}{settings.address&&<div>{settings.address}</div>}{settings.gstin&&<div>GSTIN: {settings.gstin}</div>}</div></div><div><b>Quick links</b><div className="mt-3 flex flex-col gap-2 text-sm text-white/60"><a href="#products">Products</a><a href="/blog">Blog</a>{pages.slice(0,5).map(p=><a key={p.id} href={`#page-${p.slug}`}>{p.title}</a>)}</div></div></div><div className="border-t border-white/10 px-4 py-5 text-center text-xs text-white/40">{d.footer?.copyright_text||`© ${new Date().getFullYear()} ${settings.website_name||'PinkBox'}. All rights reserved.`}</div></footer>
 {view&&<div className="fixed inset-0 z-50 bg-black/50 p-4" onClick={()=>setView(null)}><div className="mx-auto mt-10 max-w-2xl rounded-3xl bg-white p-6" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs text-gray-400">{view.sku}</p><h2 className="text-3xl font-bold">{view.title}</h2></div><button onClick={()=>setView(null)}><X/></button></div><p className="mt-5 text-slate-600">{view.description||view.short_description||''}</p><div className="mt-6 flex items-center justify-between"><b className="text-3xl" style={{color:primary}}>{money(view.price)}</b><button onClick={()=>add(view)} disabled={Number(view.stock_quantity||0)<1&&!view.allow_backorder} className="rounded-full px-6 py-3 font-semibold text-white disabled:opacity-40" style={{background:primary}}>Add to cart</button></div></div></div>}
 {drawer&&<div className="fixed inset-0 z-50 bg-black/40" onClick={()=>setDrawer(false)}><aside className="ml-auto flex h-full w-full max-w-md flex-col bg-white" onClick={e=>e.stopPropagation()}><div className="flex justify-between border-b p-5"><div><h2 className="text-xl font-bold">Your cart</h2><p className="text-xs text-gray-500">{count} items</p></div><button onClick={()=>setDrawer(false)}><X/></button></div><div className="flex-1 overflow-y-auto p-5">{cart.length?cart.map(x=><div key={x.id} className="flex justify-between gap-3 border-b py-4"><div><b>{x.title}</b><div className="text-sm text-gray-500">{money(x.price)}</div><div className="mt-2 flex items-center gap-3"><button onClick={()=>change(x.id,-1)} className="rounded-full border p-1"><Minus size={13}/></button><span>{x.quantity}</span><button onClick={()=>change(x.id,1)} className="rounded-full border p-1"><Plus size={13}/></button></div></div><b>{money(x.price*x.quantity)}</b></div>):<div className="grid h-full place-items-center text-gray-500">Your cart is empty.</div>}</div>{cart.length>0&&<div className="border-t p-5"><div className="flex justify-between text-sm"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="mt-2 flex justify-between text-sm"><span>Shipping</span><b>{shipping?money(shipping):'FREE'}</b></div><div className="mt-2 flex justify-between text-xl font-bold"><span>Total</span><span>{money(total)}</span></div><button onClick={()=>setCheckout(true)} className="mt-5 w-full rounded-xl py-3.5 font-semibold text-white" style={{background:primary}}>Checkout</button></div>}</aside></div>}
 {checkout&&<div className="fixed inset-0 z-[60] overflow-y-auto bg-black/50 p-4"><div className="mx-auto my-8 max-w-2xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-bold">Checkout</h2><button onClick={()=>setCheckout(false)}><X/></button></div><form onSubmit={order} onBlur={saveCart} className="mt-6 grid gap-4 sm:grid-cols-2"><input required placeholder="Full Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded-xl border px-4 py-3"/><input required placeholder="Phone / WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="rounded-xl border px-4 py-3"/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="rounded-xl border px-4 py-3"/><input required placeholder="Pincode" value={form.pincode} onChange={e=>setForm({...form,pincode:e.target.value})} className="rounded-xl border px-4 py-3"/><input required placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})} className="rounded-xl border px-4 py-3"/><input required placeholder="State" value={form.state} onChange={e=>setForm({...form,state:e.target.value})} className="rounded-xl border px-4 py-3"/><textarea required rows="3" placeholder="Delivery Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="sm:col-span-2 rounded-xl border px-4 py-3"/><input placeholder="Coupon code" value={form.coupon_code} onChange={e=>setForm({...form,coupon_code:e.target.value.toUpperCase()})} className="rounded-xl border px-4 py-3"/><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})} className="rounded-xl border px-4 py-3"><option value="cod">Cash on Delivery</option>{settings.online_payment_enabled&&<option value="online">Online Payment</option>}</select><textarea rows="2" placeholder="Order note" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} className="sm:col-span-2 rounded-xl border px-4 py-3"/><div className="sm:col-span-2 rounded-2xl bg-slate-50 p-4 flex justify-between"><span>Total</span><b>{money(total)}</b></div><button disabled={busy} className="sm:col-span-2 rounded-xl py-3.5 font-semibold text-white disabled:opacity-50" style={{background:primary}}>{busy?'Placing…':'Place order'}</button>{(err||msg)&&<div className={`sm:col-span-2 rounded-xl p-4 text-sm ${err?'bg-red-50 text-red-700':'bg-green-50 text-green-700'}`}>{err||msg}</div>}</form></div></div>}
 {msg&&!checkout&&<div className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{msg}</div>}
 </div>;
}
const Benefit=({I,t,d})=><div className="rounded-2xl border p-5"><I size={21}/><h3 className="mt-3 font-semibold">{t}</h3><p className="mt-1 text-sm text-slate-500">{d}</p></div>;
const Card=({p,primary,view,add})=>{const out=Number(p.stock_quantity||0)<1&&!p.allow_backorder;return <article className="rounded-2xl border bg-white p-4 hover:shadow-lg"><button onClick={view} className="w-full text-left"><div className="grid aspect-square place-items-center rounded-xl bg-slate-50 text-5xl font-bold text-slate-200">PB</div><p className="mt-4 text-xs font-semibold uppercase text-gray-400">{p.brand||p.sku}</p><h3 className="mt-1 min-h-12 font-semibold">{p.title}</h3><p className="mt-2 line-clamp-2 text-sm text-gray-500">{p.short_description||''}</p></button><div className="mt-4 flex items-center justify-between"><b className="text-xl" style={{color:primary}}>{money(p.price)}</b><button disabled={out} onClick={add} className="rounded-full px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" style={{background:primary}}>{out?'Out':'Add'}</button></div></article>};
