'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,ShoppingBag,Menu,X,Plus,Minus,Heart,ArrowRight,Truck,ShieldCheck,RotateCcw,Star,ChevronDown} from 'lucide-react';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const text=(v,f='')=>typeof v==='string'&&v.trim()?v:f;
export default function PinkBoxStorefront(){
 const[d,setD]=useState(null),[q,setQ]=useState(''),[cat,setCat]=useState('all'),[cart,setCart]=useState([]),[drawer,setDrawer]=useState(false),[product,setProduct]=useState(null),[mobile,setMobile]=useState(false),[checkout,setCheckout]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[form,setForm]=useState({name:'',phone:'',email:'',address:'',pincode:'',city:'',state:'',note:'',payment_method:'cod',coupon_code:''}),[sid,setSid]=useState('');
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('pinkbox_cart')||'[]'))}catch{}let s=localStorage.getItem('pinkbox_session_id');if(!s){s=`pb-${crypto.randomUUID()}`;localStorage.setItem('pinkbox_session_id',s)}setSid(s);fetch('/api/storefront',{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||'Store unavailable');setD(j)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>localStorage.setItem('pinkbox_cart',JSON.stringify(cart)),[cart]);
 const theme=d?.theme||{}, ts=theme.settings||{}, primary=theme.primary_color||'#d9295f', secondary=theme.secondary_color||'#111827', settings=d?.settings||{};
 const radius=ts.button_radius||'18px', products=d?.products||[], categories=d?.categories||[], sections=d?.sections||[], hero=d?.banners?.[0], featured=products.filter(p=>p.featured), shown=useMemo(()=>products.filter(p=>(cat==='all'||p.category_id===cat)&&(!q||[p.title,p.sku,p.brand,p.short_description,p.description].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase())))),[products,cat,q]);
 const items=featured.length?featured:shown; const count=cart.reduce((s,x)=>s+x.quantity,0),subtotal=cart.reduce((s,x)=>s+Number(x.price)*x.quantity,0),shipping=settings.shipping_enabled?(settings.free_shipping_threshold&&subtotal>=Number(settings.free_shipping_threshold)?0:Number(settings.default_shipping_charge||0)):0,total=subtotal+shipping;
 const add=p=>{setCart(a=>{const f=a.find(x=>x.id===p.id);return f?a.map(x=>x.id===p.id?{...x,quantity:Math.min(x.quantity+1,Number(p.stock_quantity||999999))}:x):[...a,{...p,quantity:1}]});setProduct(null);setDrawer(true);setNotice('Added to cart')};
 const change=(id,n)=>setCart(a=>a.map(x=>x.id===id?{...x,quantity:Math.max(0,Math.min(x.quantity+n,Number(x.stock_quantity||999999)))}:x).filter(x=>x.quantity));
 const order=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/storefront',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,session_id:sid,items:cart.map(x=>({product_id:x.id,quantity:x.quantity}))})});const j=await r.json();if(!r.ok)throw Error(j.error||'Checkout failed');setNotice(`Order ${j.order_number||j.order_id} placed successfully`);setCart([]);setCheckout(false);setDrawer(false);localStorage.removeItem('pinkbox_cart')}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(error&&!d)return <div className="pb-state"><div><b>PinkBox is temporarily unavailable</b><p>{error}</p></div></div>;if(!d)return <div className="pb-state">Loading PinkBox…</div>;
 const nav=Array.isArray(d.menu?.items)?d.menu.items:[];
 return <div className="pb-store" style={{'--pb-primary':primary,'--pb-secondary':secondary,'--pb-radius':radius,'--pb-font':theme.font_family||'Inter,system-ui,sans-serif'}}>
  <div className="pb-announcement">{ts.announcement_bar||`Free shipping on orders above ${money(settings.free_shipping_threshold||0)} · Secure checkout`}</div>
  <header className="pb-header"><div className="pb-head-inner"><button className="pb-icon mobile-only" onClick={()=>setMobile(true)}><Menu/></button><a href="/" className="pb-brand">{settings.logo_url?<img src={settings.logo_url} alt={settings.website_name||'PinkBox'}/>:<span className="pb-logo">PB</span>}<span>{settings.website_name||'PinkBox'}</span></a><nav className="pb-nav">{nav.length?nav.map((n,i)=><a key={i} href={n.url||n.href||'#products'}>{n.label||n.title||n.name}</a>):<><a href="#products">Shop</a><a href="#collections">Collections</a><a href="#about">About</a><a href="#contact">Contact</a></>}</nav><div className="pb-actions"><label className="pb-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products…"/></label><button className="pb-icon" aria-label="cart" onClick={()=>setDrawer(true)}><ShoppingBag/><i>{count}</i></button></div></div></header>
  {hero?<section className="pb-hero"><div className="pb-hero-copy"><span className="pb-eyebrow">PINKBOX EDIT</span><h1>{text(hero.title,'Everyday essentials, beautifully delivered.')}</h1><p>{text(hero.subtitle,text(settings.meta_description,'Discover products selected for quality, value and everyday comfort.'))}</p><div className="pb-hero-actions"><a className="pb-btn" href={hero.button_url||'#products'}>{text(hero.button_text,'Shop now')} <ArrowRight size={17}/></a><a className="pb-text-btn" href="#products">Explore collection</a></div></div><div className="pb-hero-media">{hero.image_url?<img src={hero.image_url} alt={hero.title||''}/>:<div className="pb-hero-placeholder"><span>PB</span></div>}<div className="pb-float-card"><Star fill="currentColor" size={15}/><b>Quality first</b><small>Curated for you</small></div></div></section>:<section className="pb-hero pb-hero-empty"><div className="pb-hero-copy"><span className="pb-eyebrow">WELCOME TO {settings.website_name||'PINKBOX'}</span><h1>Better products. Better everyday.</h1><p>{text(settings.meta_description,'A modern shopping experience built around your needs.')}</p><a className="pb-btn" href="#products">Shop now <ArrowRight size={17}/></a></div></section>}
  <section className="pb-benefits"><div><Truck/><span><b>Fast delivery</b><small>Reliable shipping across India</small></span></div><div><ShieldCheck/><span><b>Trusted quality</b><small>Products you can count on</small></span></div><div><RotateCcw/><span><b>Easy support</b><small>We are here when you need us</small></span></div></section>
  <section id="collections" className="pb-section"><div className="pb-section-head"><div><span className="pb-eyebrow">SHOP BY CATEGORY</span><h2>Find your favourites</h2></div><a href="#products">View all <ArrowRight size={16}/></a></div><div className="pb-cats">{categories.map(c=><button key={c.id} onClick={()=>{setCat(c.id);document.getElementById('products')?.scrollIntoView({behavior:'smooth'})}}>{c.image_url?<img src={c.image_url} alt=""/>:<span>{String(c.name||'').slice(0,1)}</span>}<b>{c.name}</b></button>)}</div></section>
  <section id="products" className="pb-section pb-products"><div className="pb-section-head"><div><span className="pb-eyebrow">THE COLLECTION</span><h2>{cat==='all'?'Featured products':categories.find(c=>c.id===cat)?.name||'Products'}</h2></div><div className="pb-filter"><button onClick={()=>setCat('all')}>All</button>{categories.slice(0,4).map(c=><button key={c.id} onClick={()=>setCat(c.id)} className={cat===c.id?'active':''}>{c.name}</button>)}</div></div><div className="pb-grid">{(cat==='all'?items:shown).slice(0,12).map(p=><ProductCard key={p.id} p={p} onOpen={()=>setProduct(p)} onAdd={()=>add(p)}/>)}</div>{!shown.length&&<div className="pb-empty">No products found for this search.</div>}</section>
  {sections.map(s=><CustomSection key={s.id} s={s} primary={primary}/>)}
  {d.blog?.length>0&&<section className="pb-section"><div className="pb-section-head"><div><span className="pb-eyebrow">FROM THE JOURNAL</span><h2>Stories & updates</h2></div><a href="/blog">View journal <ArrowRight size={16}/></a></div><div className="pb-blog">{d.blog.slice(0,3).map(b=><a href={`/blog/${b.slug}`} key={b.id}>{b.cover_image_url&&<img src={b.cover_image_url} alt=""/>}<div><span>{new Date(b.published_at||Date.now()).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</span><h3>{b.title}</h3><p>{b.excerpt||''}</p></div></a>)}</div></section>}
  <footer id="contact" className="pb-footer"><div className="pb-footer-main"><div><a className="pb-brand pb-brand-light" href="/">{settings.logo_url?<img src={settings.logo_url} alt=""/>:<span className="pb-logo">PB</span>}<span>{settings.website_name||'PinkBox'}</span></a><p>{text(settings.meta_description,'Quality products, simple shopping and reliable delivery.')}</p></div><div><b>Explore</b><a href="#products">Shop</a><a href="#collections">Collections</a><a href="/blog">Journal</a></div><div id="about"><b>Company</b>{(d.pages||[]).slice(0,4).map(p=><a key={p.id} href={`#page-${p.slug}`}>{p.title}</a>)}</div><div><b>Contact</b>{settings.phone&&<span>{settings.phone}</span>}{settings.email&&<span>{settings.email}</span>}{settings.address&&<span>{settings.address}</span>}</div></div><div className="pb-footer-bottom">{d.footer?.copyright_text||`© ${new Date().getFullYear()} ${settings.website_name||'PinkBox'}. All rights reserved.`}</div></footer>
  {d.pages?.map(p=><section id={`page-${p.slug}`} className="pb-page" key={p.id}><div><h2>{p.title}</h2><p>{text(p.content?.text,text(p.content?.body,''))}</p></div></section>)}
  {mobile&&<div className="pb-overlay" onClick={()=>setMobile(false)}><aside className="pb-mobile" onClick={e=>e.stopPropagation()}><button onClick={()=>setMobile(false)}><X/></button><div className="pb-mobile-links">{nav.length?nav.map((n,i)=><a key={i} onClick={()=>setMobile(false)} href={n.url||n.href||'#products'}>{n.label||n.title||n.name}</a>):<><a href="#products">Shop</a><a href="#collections">Collections</a><a href="#about">About</a><a href="#contact">Contact</a></>}</div></aside></div>}
  {product&&<div className="pb-overlay" onClick={()=>setProduct(null)}><div className="pb-product-modal" onClick={e=>e.stopPropagation()}><button className="pb-modal-close" onClick={()=>setProduct(null)}><X/></button><div className="pb-modal-media">{product.image_url?<img src={product.image_url} alt={product.title}/>:<span>PB</span>}</div><div className="pb-modal-copy"><span className="pb-eyebrow">{product.brand||product.sku}</span><h2>{product.title}</h2><p>{product.description||product.short_description||''}</p><div className="pb-price">{money(product.price)} {product.compare_at_price&&<del>{money(product.compare_at_price)}</del>}</div><button className="pb-btn" disabled={Number(product.stock_quantity||0)<1&&!product.allow_backorder} onClick={()=>add(product)}>{Number(product.stock_quantity||0)>0||product.allow_backorder?'Add to cart':'Out of stock'} <ShoppingBag size={17}/></button></div></div></div>}
  {drawer&&<div className="pb-overlay" onClick={()=>setDrawer(false)}><aside className="pb-cart" onClick={e=>e.stopPropagation()}><div className="pb-cart-head"><div><span className="pb-eyebrow">YOUR BAG</span><h2>Shopping cart</h2></div><button onClick={()=>setDrawer(false)}><X/></button></div><div className="pb-cart-items">{cart.length?cart.map(x=><div className="pb-cart-item" key={x.id}><div><b>{x.title}</b><span>{money(x.price)}</span><div><button onClick={()=>change(x.id,-1)}><Minus size={13}/></button><span>{x.quantity}</span><button onClick={()=>change(x.id,1)}><Plus size={13}/></button></div></div><strong>{money(Number(x.price)*x.quantity)}</strong></div>):<div className="pb-cart-empty"><ShoppingBag size={32}/><p>Your cart is empty.</p><a href="#products" onClick={()=>setDrawer(false)}>Start shopping</a></div>}</div>{cart.length>0&&<div className="pb-cart-foot"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Shipping</span><b>{shipping?money(shipping):'FREE'}</b></div><div className="total"><span>Total</span><b>{money(total)}</b></div><button className="pb-btn" onClick={()=>setCheckout(true)}>Checkout <ArrowRight size={17}/></button></div>}</aside></div>}
  {checkout&&<div className="pb-overlay pb-checkout-overlay"><div className="pb-checkout" onClick={e=>e.stopPropagation()}><div className="pb-cart-head"><div><span className="pb-eyebrow">SECURE CHECKOUT</span><h2>Delivery details</h2></div><button onClick={()=>setCheckout(false)}><X/></button></div><form onSubmit={order}><div className="pb-form-grid">{[['name','Full name'],['phone','Phone'],['email','Email'],['pincode','Pincode'],['city','City'],['state','State']].map(([k,l])=><input key={k} required={['name','phone'].includes(k)} placeholder={l} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<textarea required placeholder="Delivery address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><textarea placeholder="Order note (optional)" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></div><div className="pb-payment"><label><input type="radio" checked={form.payment_method==='cod'} onChange={()=>setForm({...form,payment_method:'cod'})}/> Cash on Delivery</label>{settings.online_payment_enabled&&<label><input type="radio" checked={form.payment_method==='online'} onChange={()=>setForm({...form,payment_method:'online'})}/> Online payment</label>}</div>{error&&<p className="pb-error">{error}</p>}<button className="pb-btn" disabled={busy}>{busy?'Placing order…':`Place order · ${money(total)}`}</button></form></div></div>}
  {notice&&<button className="pb-toast" onClick={()=>setNotice('')}>{notice}</button>}
 </div>
}
function ProductCard({p,onOpen,onAdd}){const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;return <article className="pb-card"><button className="pb-card-media" onClick={onOpen}>{p.image_url?<img src={p.image_url} alt={p.title}/>:<span>PB</span>}{p.compare_at_price&&<em>SALE</em>}<i><Heart size={17}/></i></button><div className="pb-card-body"><span>{p.brand||'PinkBox'}</span><button onClick={onOpen}><h3>{p.title}</h3></button><div className="pb-card-bottom"><div><b>{money(p.price)}</b>{p.compare_at_price&&<del>{money(p.compare_at_price)}</del>}</div><button onClick={onAdd} disabled={Number(p.stock_quantity||0)<1&&!p.allow_backorder}>Add <Plus size={15}/></button></div></div></article>}
function CustomSection({s,primary}){const x=s.settings||{};return <section className={`pb-custom pb-custom-${s.section_type||'content'}`} style={{'--section-accent':primary}}><div><span className="pb-eyebrow">{String(s.section_type||'FEATURE').replaceAll('_',' ')}</span><h2>{s.title||x.heading||'Made for everyday.'}</h2><p>{x.description||x.text||'A section managed from your PinkBox Admin.'}</p>{x.button_text&&<a className="pb-btn" href={x.button_url||'#products'}>{x.button_text}<ArrowRight size={17}/></a>}</div>{x.image_url&&<img src={x.image_url} alt=""/>}</section>}
