'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BadgeCheck,Heart,Search,ShieldCheck,ShoppingBag,Star,Truck,Sparkles,Instagram} from 'lucide-react';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const pick=(v,f='')=>typeof v==='string'&&v.trim()?v:f;
export default function PinkBoxHome(){
 const [data,setData]=useState(null),[slide,setSlide]=useState(0),[query,setQuery]=useState(''),[wish,setWish]=useState([]),[error,setError]=useState('');
 useEffect(()=>{try{setWish(JSON.parse(localStorage.getItem('pinkbox_wishlist')||'[]'))}catch{} fetch('/api/storefront',{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||'Store unavailable');setData(j)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>localStorage.setItem('pinkbox_wishlist',JSON.stringify(wish)),[wish]);
 const banners=useMemo(()=>data?.banners?.filter(b=>b?.is_active!==false)||[],[data]);
 useEffect(()=>{if(banners.length<2)return;const id=setInterval(()=>setSlide(i=>(i+1)%banners.length),5500);return()=>clearInterval(id)},[banners.length]);
 useEffect(()=>{if(slide>=banners.length)setSlide(0)},[slide,banners.length]);
 if(error&&!data)return <main className="pb-home-state"><b>PinkBox is temporarily unavailable</b><p>{error}</p></main>;
 if(!data)return <main className="pb-home-state">Loading PinkBox…</main>;
 const s=data.settings||{},theme=data.theme||{},cats=data.categories||[],products=data.products||[],sections=(data.sections||[]).filter(x=>x?.is_active!==false),blog=(data.blog||[]).filter(Boolean).slice(0,3),nav=Array.isArray(data.menu?.items)?data.menu.items:[];
 const activeBanner=banners[slide]; const featured=products.filter(p=>p.featured&&p.is_active!==false);const arrivals=(featured.length?featured:products.filter(p=>p.is_active!==false)).slice(0,8);
 const filtered=products.filter(p=>p.is_active!==false&&(!query||[p.title,p.brand,p.sku,p.short_description].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())))).slice(0,4);const shopProducts=query?filtered:arrivals;
 const toggle=id=>setWish(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]);
 return <main className="pb-home" style={{'--pb-primary':theme.primary_color||'#d72d61'}}>
 <div className="pb-home-announcement">{pick(theme.settings?.announcement_bar,`Free shipping above ${money(s.free_shipping_threshold||0)} · Secure checkout · Easy support`)}</div>
 <header className="pb-home-header"><div className="pb-home-top"><a href="/" className="pb-home-brand">{s.logo_url?<img src={s.logo_url} alt={s.website_name||'PinkBox'}/>:<span>PB</span>}<strong>{s.website_name||'PinkBox'}</strong></a><nav>{nav.length?nav.slice(0,6).map((n,i)=><a key={i} href={n.url||n.href||'#collections'}>{n.label||n.title||n.name}</a>):<><a href="#collections">Shop</a><a href="#new-arrivals">New Arrivals</a><a href="#story">Our Story</a><a href="#journal">Journal</a></>}</nav><div className="pb-home-tools"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search"/></label><a href="/account" aria-label="Account">◯</a><a href="/wishlist" aria-label="Wishlist"><Heart size={19} fill={wish.length?'currentColor':'none'}/><i>{wish.length}</i></a><a href="/cart" aria-label="Cart"><ShoppingBag size={19}/></a></div></div></header>
 <section className="pb-home-hero"><div className="pb-home-hero-copy"><span className="pb-home-kicker">PINKBOX / EVERYDAY EDIT</span><h1>{pick(activeBanner?.title,'Everyday essentials, made beautifully.')}</h1><p>{pick(activeBanner?.subtitle,pick(s.meta_description,'Quality essentials, thoughtful value and a smoother way to shop.'))}</p><div className="pb-home-hero-actions"><a className="pb-home-primary" href={activeBanner?.button_url||'#new-arrivals'}>{pick(activeBanner?.button_text,'Shop now')} <ArrowRight size={17}/></a><a className="pb-home-ghost" href="#collections">Explore collection</a></div><div className="pb-home-proof"><span><BadgeCheck size={15}/>Quality checked</span><span><Truck size={15}/>Reliable delivery</span><span><ShieldCheck size={15}/>Secure checkout</span></div></div><div className="pb-home-hero-art">{activeBanner?.image_url?<img src={activeBanner.image_url} alt={activeBanner.title||''}/>:<div className="pb-art-fallback"><Sparkles/><b>PB</b></div>}<div className="pb-doodle pb-doodle-one">✦</div><div className="pb-doodle pb-doodle-two">◌</div><div className="pb-hero-note"><Star size={14} fill="currentColor"/><b>Made with care</b><small>Designed for everyday comfort</small></div><div className="pb-slider-nav">{banners.length>1&&<><button onClick={()=>setSlide(i=>(i-1+banners.length)%banners.length)} aria-label="Previous banner"><ArrowLeft size={16}/></button><span>{slide+1} / {banners.length}</span><button onClick={()=>setSlide(i=>(i+1)%banners.length)} aria-label="Next banner"><ArrowRight size={16}/></button></>}</div></div></section>
 <section className="pb-home-marquee"><div>{cats.slice(0,8).map((c,i)=><span key={c.id||i}>{c.name}<em>✦</em></span>)}</div></section>
 <section id="collections" className="pb-home-section pb-home-categories"><div className="pb-home-head"><div><span>SHOP BY CATEGORY</span><h2>A collection for every day</h2></div><a href="#new-arrivals">View products <ArrowRight size={16}/></a></div>{cats.length?<div className="pb-category-grid">{cats.slice(0,6).map(c=><a key={c.id} href={`/collections/${c.slug}`} className="pb-category-card">{c.image_url?<img src={c.image_url} alt=""/>:<div className="pb-category-placeholder">{String(c.name||'P').slice(0,1)}</div>}<div><b>{c.name}</b><ArrowRight size={16}/></div></a>)}</div>:<div className="pb-home-empty">Publish categories from PinkBox Admin to fill this section.</div>}</section>
 <section id="new-arrivals" className="pb-home-section pb-home-products"><div className="pb-home-head"><div><span>{query?'SEARCH RESULTS':'NEW / FEATURED'}</span><h2>{query?`Results for “${query}”`:'New arrivals worth knowing'}</h2></div><a href="/wishlist">Saved items <Heart size={15}/></a></div><div className="pb-product-grid">{shopProducts.map(p=><article key={p.id} className="pb-product-card"><a className="pb-product-image" href={`/products/${p.slug}`}>{p.image_url?<img src={p.image_url} alt={p.title}/>:<b>PB</b>}{p.compare_at_price&&<em>SALE</em>}</a><button className="pb-heart" onClick={()=>toggle(p.id)} aria-label="Save to wishlist"><Heart size={17} fill={wish.includes(p.id)?'currentColor':'none'}/></button><div className="pb-product-info"><span>{p.brand||'PINKBOX'}</span><a href={`/products/${p.slug}`}><h3>{p.title}</h3></a><div><strong>{money(p.price)}</strong>{p.compare_at_price&&<del>{money(p.compare_at_price)}</del>}<a href={`/products/${p.slug}`} className="pb-view">View <ArrowRight size={14}/></a></div></div></article>)}</div>{!shopProducts.length&&<div className="pb-home-empty">No products available yet.</div>}</section>
 <section id="story" className="pb-home-editorial"><div className="pb-editorial-art"><div className="pb-illustration"><div className="pb-illustration-circle"></div><div className="pb-illustration-card">PB</div><span>✿</span><span>◌</span><span>✦</span></div></div><div className="pb-editorial-copy"><span>THE PINKBOX PHILOSOPHY</span><h2>Useful should still feel beautiful.</h2><p>PinkBox brings product discovery, thoughtful presentation and simple shopping together in one calm experience.</p><a className="pb-home-primary" href="#new-arrivals">Discover the collection <ArrowRight size={17}/></a></div></section>
 {sections.slice(0,3).map((sec,i)=><section key={sec.id||i} className={`pb-home-custom ${i%2?'alt':''}`}><div><span>{String(sec.section_type||'FEATURE').replaceAll('_',' ')}</span><h2>{sec.title||sec.settings?.heading||'Designed around your everyday.'}</h2><p>{sec.settings?.description||sec.settings?.text||'A premium content block managed from PinkBox Admin.'}</p>{sec.settings?.button_text&&<a className="pb-home-primary" href={sec.settings?.button_url||'#new-arrivals'}>{sec.settings.button_text}<ArrowRight size={17}/></a>}</div>{sec.settings?.image_url&&<img src={sec.settings.image_url} alt=""/>}</section>)}
 <section className="pb-home-benefits"><div><Truck/><b>Fast delivery</b><small>Reliable shipping across India</small></div><div><BadgeCheck/><b>Trusted quality</b><small>Clear products and pricing</small></div><div><Heart/><b>Save favourites</b><small>Wishlist for easy re-shopping</small></div><div><ShieldCheck/><b>Secure checkout</b><small>Simple COD and online payment</small></div></section>
 {blog.length>0&&<section id="journal" className="pb-home-section pb-home-journal"><div className="pb-home-head"><div><span>FROM THE JOURNAL</span><h2>Ideas, guides & updates</h2></div><a href="/blog">View journal <ArrowRight size={16}/></a></div><div className="pb-journal-grid">{blog.map(post=><a key={post.id} href={`/blog/${post.slug}`}>{post.cover_image_url?<img src={post.cover_image_url} alt=""/>:<div className="pb-journal-placeholder">PB</div>}<div><small>{new Date(post.published_at||Date.now()).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</small><h3>{post.title}</h3><p>{post.excerpt||''}</p><span>Read story <ArrowRight size={14}/></span></div></a>)}</div></section>}
 <section className="pb-home-cta"><div><span>KEEP IN TOUCH</span><h2>More from PinkBox, without the noise.</h2><p>New launches, useful updates and everyday inspiration—kept simple.</p></div><a className="pb-home-light" href={s.email?`mailto:${s.email}`:'#contact'}>Stay connected <ArrowRight size={17}/></a></section>
 <footer id="contact" className="pb-home-footer"><div className="pb-footer-brand"><a href="/" className="pb-home-brand">{s.logo_url?<img src={s.logo_url} alt=""/>:<span>PB</span>}<strong>{s.website_name||'PinkBox'}</strong></a><p>{pick(s.meta_description,'Quality products, simple shopping and reliable delivery.')}</p></div><div><b>Explore</b><a href="#collections">Shop</a><a href="#new-arrivals">New arrivals</a><a href="#story">Our story</a><a href="/blog">Journal</a></div><div><b>Support</b><a href="/account">Account</a><a href="/wishlist">Wishlist</a><a href="/cart">Cart</a></div><div><b>Contact</b>{s.phone&&<span>{s.phone}</span>}{s.email&&<span>{s.email}</span>}{s.address&&<span>{s.address}</span>}<span><Instagram size={15}/> Follow PinkBox</span></div></footer>
 <div className="pb-home-bottom">{data.footer?.copyright_text||`© ${new Date().getFullYear()} ${s.website_name||'PinkBox'}. All rights reserved.`}</div>
 </main>;
}
