'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Check, Eye, Image as ImageIcon, LayoutTemplate, Menu, Plus, RefreshCw, Save, Settings2, Trash2, X } from 'lucide-react';

const tabs = [
  ['overview', 'Overview', LayoutTemplate],
  ['header', 'Header & Branding', Menu],
  ['hero', 'Hero Banners', ImageIcon],
  ['sections', 'Homepage Sections', Settings2],
  ['footer', 'Footer', LayoutTemplate],
];
const sectionTypes = ['editorial','products','categories','benefits','blog','custom','cta'];
const api = async (url, options) => { const r = await fetch(url, options); const j = await r.json().catch(() => ({})); if (!r.ok) throw Error(j.error || 'Request failed'); return j; };
const input = 'w-full rounded-xl border border-gray-300 bg-white px-3 py-2.5 text-sm text-gray-900 outline-none focus:border-gray-900 focus:ring-2 focus:ring-gray-900/10';
const slugify = s => String(s || '').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const blankBanner = { title:'', subtitle:'', image_url:'', mobile_image_url:'', button_text:'Shop now', button_url:'/products', sort_order:10, is_active:true, starts_at:'', ends_at:'' };
const blankSection = { section_type:'editorial', title:'', settings:{ description:'', text:'', heading:'', button_text:'', button_url:'', image_url:'', image_alt:'', source:'featured', limit:4 }, sort_order:10, is_active:true };
const blankFooter = { columns:[], social_links:{}, copyright_text:'' };

function Notice({ error, notice }) { return error || notice ? <div className={`flex items-center gap-2 rounded-xl border px-4 py-3 text-sm ${error ? 'border-red-200 bg-red-50 text-red-700' : 'border-green-200 bg-green-50 text-green-700'}`}>{error || <><Check size={16}/>{notice}</>}</div> : null; }
function Field({ label, value, onChange, placeholder, type='text' }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-700">{label}</span><input type={type} value={value ?? ''} onChange={onChange} placeholder={placeholder} className={input}/></label>; }
function Switch({ label, checked, onChange }) { return <label className="inline-flex items-center gap-2 text-sm font-medium text-gray-800"><input type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 rounded border-gray-300"/>{label}</label>; }

export default function PinkBoxHomepageBuilder(){
  const [tab,setTab] = useState('overview');
  const [loading,setLoading] = useState(true), [saving,setSaving] = useState(false), [error,setError] = useState(''), [notice,setNotice] = useState('');
  const [settings,setSettings] = useState({website_name:'PinkBox',logo_url:'',favicon_url:'',phone:'',whatsapp_number:'',email:'',address:'',meta_title:'',meta_description:''});
  const [theme,setTheme] = useState({theme_name:'PinkBox',announcement_bar:{enabled:true,text:''},header_settings:{logo_position:'center',show_search:true,show_account:true,show_wishlist:true,show_cart:true}});
  const [nav,setNav] = useState({location:'header',name:'Main Menu',items:[]});
  const [footer,setFooter] = useState(blankFooter);
  const [banners,setBanners] = useState([]); const [sections,setSections] = useState([]); const [categories,setCategories] = useState([]);
  const [bannerDraft,setBannerDraft] = useState(null); const [sectionDraft,setSectionDraft] = useState(null);

  const load = async () => {
    setLoading(true); setError(''); setNotice('');
    try {
      const [s,t,n,f,b,h,c] = await Promise.all([
        api('/api/website/settings'), api('/api/website/phase4?resource=theme'), api('/api/website/navigation'),
        api('/api/website/phase4?resource=footer'), api('/api/website/banners'), api('/api/website/homepage-sections'), api('/api/website/categories')
      ]);
      setSettings(s.data || {}); setTheme(t.data || {});
      const menus = Array.isArray(n.data) ? n.data : []; setNav(menus.find(x=>x.location==='header') || menus[0] || {location:'header',name:'Main Menu',items:[]});
      setFooter(f.data || blankFooter); setBanners(Array.isArray(b.data)?b.data:[]); setSections(Array.isArray(h.data)?h.data:[]); setCategories(Array.isArray(c.data)?c.data:[]);
    } catch(e){ setError(e.message); } finally { setLoading(false); }
  };
  useEffect(()=>{load()},[]);
  useEffect(()=>{ if(!error&&!loading) { const t=setTimeout(()=>setNotice(''),2400); return ()=>clearTimeout(t); } },[notice,error,loading]);

  const sortedBanners = useMemo(()=>[...banners].sort((a,b)=>(Number(a.sort_order)||0)-(Number(b.sort_order)||0)),[banners]);
  const sortedSections = useMemo(()=>[...sections].sort((a,b)=>(Number(a.sort_order)||0)-(Number(b.sort_order)||0)),[sections]);
  const save = async (url, body, method='POST') => { setSaving(true); setError(''); setNotice(''); try { await api(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); setNotice('Saved successfully.'); await load(); } catch(e){setError(e.message)} finally {setSaving(false)} };
  const remove = async (resource,id) => { if(!confirm('Delete this item?')) return; try { await api(`/api/website/${resource}?id=${id}`,{method:'DELETE'}); setNotice('Deleted successfully.'); await load(); } catch(e){setError(e.message)} };
  const swapOrder = async (rows, idx, dir, resource) => { const other=idx+dir; if(other<0||other>=rows.length)return; const a=rows[idx],b=rows[other]; try { await Promise.all([api(`/api/website/${resource}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:a.id,sort_order:b.sort_order})}),api(`/api/website/${resource}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.id,sort_order:a.sort_order})})]); setNotice('Order updated.'); await load(); } catch(e){setError(e.message)} };

  const updateSettings = async e => { e.preventDefault(); await save('/api/website/settings',settings); };
  const updateTheme = async e => { e.preventDefault(); await save('/api/website/phase4?resource=theme',theme); };
  const updateNav = async e => { e.preventDefault(); await save('/api/website/navigation',nav,nav.id?'PATCH':'POST'); };
  const updateFooter = async e => { e.preventDefault(); await save('/api/website/phase4?resource=footer',footer); };

  const addBanner = async e => { e.preventDefault(); await save('/api/website/banners',bannerDraft||blankBanner); setBannerDraft(null); };
  const editBanner = row => setBannerDraft({...row});
  const addSection = async e => { e.preventDefault(); const p={...sectionDraft, settings:typeof sectionDraft.settings==='string'?JSON.parse(sectionDraft.settings):sectionDraft.settings}; await save('/api/website/homepage-sections',p); setSectionDraft(null); };
  const editSection = row => setSectionDraft({...row,settings:JSON.stringify(row.settings||{},null,2)});

  if(loading) return <div className="flex min-h-[420px] items-center justify-center text-sm text-gray-500"><RefreshCw size={18} className="mr-2 animate-spin"/>Loading Website Builder…</div>;
  return <div className="space-y-5 text-gray-900">
    <div className="rounded-3xl border border-gray-200 bg-gradient-to-br from-white via-rose-50/60 to-pink-50/70 p-5 shadow-sm sm:p-6">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div><div className="mb-2 inline-flex items-center gap-2 rounded-full border bg-white/80 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-gray-600"><LayoutTemplate size={14}/> PinkBox Website Builder</div><h1 className="text-3xl font-semibold tracking-tight">Control the storefront from one place.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-600">Branding, header, hero slider, homepage sections, categories, footer and merchandising order are managed here and pushed through the same company-scoped website APIs.</p></div>
        <div className="flex flex-wrap gap-2"><a href="/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><Eye size={16}/>Preview Storefront</a><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><RefreshCw size={16}/>Refresh</button></div>
      </div>
    </div>
    <Notice error={error} notice={notice}/>
    <div className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2 shadow-sm">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold ${tab===id?'bg-gray-900 text-white':'text-gray-600 hover:bg-gray-50'}`}><Icon size={16}/>{label}</button>)}</div>

    {tab==='overview'&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      {[['Hero banners',banners.length,'Editable slides + CTA'],['Homepage sections',sections.length,'Ordered content blocks'],['Categories',categories.length,'Images + merchandising'],['Footer columns',(footer.columns||[]).length,'Structured navigation']].map(([a,b,c])=><div key={a} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="text-sm font-semibold text-gray-500">{a}</div><div className="mt-2 text-3xl font-semibold">{b}</div><div className="mt-1 text-xs text-gray-500">{c}</div></div>)}
      <div className="md:col-span-2 xl:col-span-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 font-semibold">Homepage live structure</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{['Announcement bar','Logo + search + account + wishlist + cart','Hero slider','Category marquee + cards','New / featured products','Editorial illustration','Admin custom blocks','Benefits / trust strip','Journal / blog','Premium CTA','Footer + social'].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-gray-50 p-3 text-sm"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-white text-xs font-bold shadow-sm">{i+1}</span>{x}</div>)}</div></div>
    </div>}

    {tab==='header'&&<div className="grid gap-5 xl:grid-cols-[1fr_420px]">
      <form onSubmit={updateSettings} className="space-y-5 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="font-semibold">Brand & contact</h2><p className="mt-1 text-xs text-gray-500">These values feed the storefront header, contact areas and SEO defaults.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Website Name" value={settings.website_name} onChange={e=>setSettings({...settings,website_name:e.target.value})}/><Field label="Logo URL" value={settings.logo_url} onChange={e=>setSettings({...settings,logo_url:e.target.value})}/><Field label="Favicon URL" value={settings.favicon_url} onChange={e=>setSettings({...settings,favicon_url:e.target.value})}/><Field label="Phone" value={settings.phone} onChange={e=>setSettings({...settings,phone:e.target.value})}/><Field label="WhatsApp" value={settings.whatsapp_number} onChange={e=>setSettings({...settings,whatsapp_number:e.target.value})}/><Field label="Email" value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})}/></div><Field label="Address" value={settings.address} onChange={e=>setSettings({...settings,address:e.target.value})}/><div className="flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white"><Save size={16}/>{saving?'Saving…':'Save Brand'}</button></div></form>
      <div className="space-y-5"><form onSubmit={updateTheme} className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="font-semibold">Announcement bar</div><Switch label="Show announcement" checked={theme.announcement_bar?.enabled} onChange={v=>setTheme({...theme,announcement_bar:{...(theme.announcement_bar||{}),enabled:v}})}/><Field label="Announcement text" value={theme.announcement_bar?.text||''} onChange={e=>setTheme({...theme,announcement_bar:{...(theme.announcement_bar||{}),text:e.target.value}})} placeholder="Free shipping above ₹499"/><div className="flex justify-end"><button className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white"><Save size={16}/>Save Header</button></div></form><form onSubmit={updateNav} className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="font-semibold">Header navigation</div><div className="grid gap-4 sm:grid-cols-2"><Field label="Menu Name" value={nav.name} onChange={e=>setNav({...nav,name:e.target.value})}/><Field label="Location" value={nav.location||'header'} onChange={e=>setNav({...nav,location:e.target.value})}/></div><label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-700">Items JSON</span><textarea rows={10} value={JSON.stringify(nav.items||[],null,2)} onChange={e=>{try{setNav({...nav,items:JSON.parse(e.target.value)})}catch{}}} className={`${input} font-mono text-xs`}/></label><div className="flex justify-end"><button className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white"><Save size={16}/>Save Menu</button></div></form></div>
    </div>}

    {tab==='hero'&&<div className="space-y-5">
      <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Hero slider</h2><p className="mt-1 text-xs text-gray-500">Desktop/mobile images, copy, CTA, publish window and slide order.</p></div><button onClick={()=>setBannerDraft({...blankBanner,sort_order:(sortedBanners.length+1)*10})} className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16}/>Add Slide</button></div></div>
      <div className="space-y-3">{sortedBanners.map((b,i)=><div key={b.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="h-28 w-full overflow-hidden rounded-xl bg-gray-100 sm:w-52">{b.image_url?<img src={b.image_url} alt={b.title||'Banner'} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs text-gray-400">No image</div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{b.title||'Untitled slide'}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${b.is_active?'bg-emerald-50 text-emerald-700':'bg-gray-100 text-gray-500'}`}>{b.is_active?'LIVE':'HIDDEN'}</span></div><p className="mt-1 text-sm text-gray-500">{b.subtitle||'No subtitle'} · {b.button_text||'No CTA'} → {b.button_url||'#'}</p><div className="mt-2 text-xs text-gray-400">Order {b.sort_order ?? '—'}{b.starts_at?' · starts '+new Date(b.starts_at).toLocaleString():''}{b.ends_at?' · ends '+new Date(b.ends_at).toLocaleString():''}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>swapOrder(sortedBanners,i,-1,'banners')} disabled={i===0} className="rounded-lg border p-2 disabled:opacity-30"><ArrowUp size={16}/></button><button onClick={()=>swapOrder(sortedBanners,i,1,'banners')} disabled={i===sortedBanners.length-1} className="rounded-lg border p-2 disabled:opacity-30"><ArrowDown size={16}/></button><button onClick={()=>editBanner(b)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Edit</button><button onClick={()=>remove('banners',b.id)} className="rounded-lg border p-2 text-red-600"><Trash2 size={16}/></button></div></div></div>)}{!sortedBanners.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-gray-500">No hero slides yet.</div>}</div>
      {bannerDraft&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-3" onMouseDown={e=>e.target===e.currentTarget&&setBannerDraft(null)}><form onSubmit={async e=>{e.preventDefault();await save('/api/website/banners',bannerDraft,bannerDraft.id?'PATCH':'POST');setBannerDraft(null)}} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">{bannerDraft.id?'Edit':'Add'} hero slide</h2><p className="mt-1 text-xs text-gray-500">Use public image URLs or URLs coming from your existing asset setup.</p></div><button type="button" onClick={()=>setBannerDraft(null)} className="rounded-lg p-2 hover:bg-gray-100"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Title" value={bannerDraft.title} onChange={e=>setBannerDraft({...bannerDraft,title:e.target.value})}/><Field label="Subtitle" value={bannerDraft.subtitle} onChange={e=>setBannerDraft({...bannerDraft,subtitle:e.target.value})}/><Field label="Desktop Image URL" value={bannerDraft.image_url} onChange={e=>setBannerDraft({...bannerDraft,image_url:e.target.value})}/><Field label="Mobile Image URL" value={bannerDraft.mobile_image_url} onChange={e=>setBannerDraft({...bannerDraft,mobile_image_url:e.target.value})}/><Field label="Button Text" value={bannerDraft.button_text} onChange={e=>setBannerDraft({...bannerDraft,button_text:e.target.value})}/><Field label="Button URL" value={bannerDraft.button_url} onChange={e=>setBannerDraft({...bannerDraft,button_url:e.target.value})}/><Field label="Sort Order" type="number" value={bannerDraft.sort_order} onChange={e=>setBannerDraft({...bannerDraft,sort_order:Number(e.target.value)})}/><Field label="Starts At" type="datetime-local" value={bannerDraft.starts_at||''} onChange={e=>setBannerDraft({...bannerDraft,starts_at:e.target.value})}/><Field label="Ends At" type="datetime-local" value={bannerDraft.ends_at||''} onChange={e=>setBannerDraft({...bannerDraft,ends_at:e.target.value})}/></div><div className="mt-4"><Switch label="Active" checked={bannerDraft.is_active} onChange={v=>setBannerDraft({...bannerDraft,is_active:v})}/></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setBannerDraft(null)} className="rounded-xl border px-4 py-2.5 text-sm font-medium">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white"><Save size={16}/>{saving?'Saving…':'Save Slide'}</button></div></form></div>}
    </div>}

    {tab==='sections'&&<div className="space-y-5"><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Homepage sections</h2><p className="mt-1 text-xs text-gray-500">These blocks map to the storefront composition: products, categories, editorial, benefits, journal, CTA and custom content.</p></div><button onClick={()=>setSectionDraft({...blankSection,sort_order:(sortedSections.length+1)*10})} className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16}/>Add Section</button></div></div><div className="space-y-3">{sortedSections.map((s,i)=><div key={s.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-rose-50 text-sm font-bold text-rose-700">{i+1}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{s.title||s.section_type||'Section'}</h3><span className="rounded-full bg-gray-100 px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-gray-600">{s.section_type}</span><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${s.is_active?'bg-emerald-50 text-emerald-700':'bg-gray-100 text-gray-500'}`}>{s.is_active?'ACTIVE':'HIDDEN'}</span></div><p className="mt-1 line-clamp-2 text-sm text-gray-500">{s.settings?.description||s.settings?.text||'No description configured.'}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>swapOrder(sortedSections,i,-1,'homepage-sections')} disabled={i===0} className="rounded-lg border p-2 disabled:opacity-30"><ArrowUp size={16}/></button><button onClick={()=>swapOrder(sortedSections,i,1,'homepage-sections')} disabled={i===sortedSections.length-1} className="rounded-lg border p-2 disabled:opacity-30"><ArrowDown size={16}/></button><button onClick={()=>editSection(s)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Edit</button><button onClick={()=>remove('homepage-sections',s.id)} className="rounded-lg border p-2 text-red-600"><Trash2 size={16}/></button></div></div></div>)}{!sortedSections.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-gray-500">No custom homepage sections yet. The storefront core sections still render from products/categories/blog, and you can add managed blocks here.</div>}</div>
      {sectionDraft&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-3" onMouseDown={e=>e.target===e.currentTarget&&setSectionDraft(null)}><form onSubmit={async e=>{e.preventDefault();try{const parsed=typeof sectionDraft.settings==='string'?JSON.parse(sectionDraft.settings||'{}'):sectionDraft.settings;await save('/api/website/homepage-sections',{...sectionDraft,settings:parsed},sectionDraft.id?'PATCH':'POST');setSectionDraft(null)}catch(err){setError('Settings JSON is invalid.')}}} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">{sectionDraft.id?'Edit':'Add'} homepage section</h2><p className="mt-1 text-xs text-gray-500">Use settings for heading, description, image, CTA, source and limit. The storefront reads these values dynamically.</p></div><button type="button" onClick={()=>setSectionDraft(null)} className="rounded-lg p-2 hover:bg-gray-100"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-700">Section Type</span><select value={sectionDraft.section_type} onChange={e=>setSectionDraft({...sectionDraft,section_type:e.target.value})} className={input}>{sectionTypes.map(x=><option key={x} value={x}>{x}</option>)}</select></label><Field label="Title" value={sectionDraft.title} onChange={e=>setSectionDraft({...sectionDraft,title:e.target.value})}/><Field label="Sort Order" type="number" value={sectionDraft.sort_order} onChange={e=>setSectionDraft({...sectionDraft,sort_order:Number(e.target.value)})}/><div className="flex items-end"><Switch label="Active" checked={sectionDraft.is_active} onChange={v=>setSectionDraft({...sectionDraft,is_active:v})}/></div></div><label className="mt-4 block"><span className="mb-1.5 block text-xs font-semibold text-gray-700">Settings JSON</span><textarea rows={16} value={typeof sectionDraft.settings==='string'?sectionDraft.settings:JSON.stringify(sectionDraft.settings||{},null,2)} onChange={e=>setSectionDraft({...sectionDraft,settings:e.target.value})} className={`${input} font-mono text-xs`}/></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setSectionDraft(null)} className="rounded-xl border px-4 py-2.5 text-sm font-medium">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white"><Save size={16}/>{saving?'Saving…':'Save Section'}</button></div></form></div>}
    </div>}

    {tab==='footer'&&<div className="grid gap-5 xl:grid-cols-2"><form onSubmit={updateFooter} className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="font-semibold">Footer content</h2><p className="mt-1 text-xs text-gray-500">Structured JSON keeps footer columns and social links flexible while remaining editable from this central builder.</p></div><label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-700">Footer Columns</span><textarea rows={14} value={JSON.stringify(footer.columns||[],null,2)} onChange={e=>{try{setFooter({...footer,columns:JSON.parse(e.target.value)})}catch{}}} className={`${input} font-mono text-xs`}/></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-700">Social Links</span><textarea rows={8} value={JSON.stringify(footer.social_links||{},null,2)} onChange={e=>{try{setFooter({...footer,social_links:JSON.parse(e.target.value)})}catch{}}} className={`${input} font-mono text-xs`}/></label><Field label="Copyright" value={footer.copyright_text||''} onChange={e=>setFooter({...footer,copyright_text:e.target.value})}/><div className="flex justify-end"><button className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white"><Save size={16}/>Save Footer</button></div></form><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 font-semibold">Category merchandising</div><div className="space-y-3">{categories.slice(0,10).map(c=><div key={c.id} className="flex items-center gap-3 rounded-xl border p-3"><div className="h-12 w-12 overflow-hidden rounded-lg bg-gray-100">{c.image_url?<img src={c.image_url} alt={c.name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-[10px] text-gray-400">No image</div>}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{c.name}</div><div className="text-xs text-gray-500">Order {c.sort_order ?? 0} · {c.is_active?'active':'hidden'}</div></div><a href={`/admin/categories`} className="rounded-lg border px-3 py-2 text-xs font-semibold">Manage</a></div>)}{!categories.length&&<div className="py-8 text-center text-sm text-gray-500">No categories found.</div>}</div></div></div>}
  </div>;
}
