'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import CartLink from './CartLink';
import {ArrowLeft,ArrowRight,BadgeCheck,Heart,Search,ShieldCheck,Star,Truck,Sparkles,Phone,PackageCheck,FlaskConical,Boxes} from 'lucide-react';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const pick=(v,f='')=>typeof v==='string'&&v.trim()?v:f;
const whyUs=[
 {icon:Sparkles,title:'Ultra-soft top sheet',desc:'A gentle, cotton-feel surface designed for sensitive skin.'},
 {icon:ShieldCheck,title:'Long-lasting protection',desc:'High-capacity core locks moisture and prevents side leaks.'},
 {icon:Truck,title:'Fast, discreet delivery',desc:'Plain packaging with reliable shipping across India.'},
 {icon:BadgeCheck,title:'Anti-bacterial layer',desc:'Odour control and hygiene protection you can trust.'},
 {icon:FlaskConical,title:'Skin-safe materials',desc:'No harsh chemicals, dermatologist-friendly formulation.'},
 {icon:PackageCheck,title:'Quality checked',desc:'Every batch is checked before it reaches your door.'},
];
export default function PinkBoxHome({ initialData }){
 const data=initialData||null;
 const [slide,setSlide]=useState(0),[query,setQuery]=useState(''),[wish,setWish]=useState([]);
 useEffect(()=>localStorage.setItem('pinkbox_wishlist',JSON.stringify(wish)),[wish]);
 const banners=useMemo(()=>data?.banners?.filter(b=>b?.is_active!==false)||[],[data]);
 useEffect(()=>{if(banners.length<2)return;const id=setInterval(()=>setSlide(i=>(i+1)%banners.length),5500);return()=>clearInterval(id)},[banners.length]);
 useEffect(()=>{if(slide>=banners.length)setSlide(0)},[slide,banners.length]);
 if(!data)return <main className="pb-home-state"><b>PinkBox is temporarily unavailable</b><p>Store data could not be loaded.</p></main>;
 const s=data.settings||{},theme=data.theme||{},cats=data.categories||[],products=(data.products||[]).filter(p=>Number(p?.price||0)>0),sections=(data.sections||[]).filter(x=>x?.is_active!==false),blog=(data.blog||[]).filter(Boolean).slice(0,3),nav=Array.isArray(data.menu?.items)?data.menu.items:[],reviews=(data.reviews||[]).filter(Boolean).slice(0,3);
 const activeBanner=banners[slide]; const arrivals=products.filter(p=>p.is_active!==false).slice(0,8);
 const filtered=products.filter(p=>p.is_active!==false&&(!query||[p.title,p.brand,p.sku,p.short_description].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())))).slice(0,4);const shopProducts=query?filtered:arrivals;
 const toggle=id=>setWish(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]);
 const freeShipThreshold=Number(s.free_shipping_threshold||0);
 const freeShipLabel=freeShipThreshold>0?`free shipping above ${money(freeShipThreshold)}`:'free shipping on all orders';
 const heroImage=activeBanner?.image_url||shopProducts[0]?.image_url||null;
 const heroLine='Cotton-soft pads, discreet home delivery, COD & UPI available.';
 const whatsappNumber=String(s.whatsapp_number||s.phone||'').replace(/\\D/g,'');
 const whatsappUrl=whatsappNumber?`https://wa.me/${whatsappNumber}?text=${encodeURIComponent('Hi PinkBox, I need help with an order.')}`:'';
 return <main className="pb-home" style={{'--pb-primary':theme.primary_color||'#d72d61'}}>
 <div className="pb-home-announcement"><span>{pick(s.announcement_bar,`${freeShipLabel} · Cotton-soft comfort · Discreet delivery`)}</span></div>
 <header className="pb-home-header"><div className="pb-home-top"><Link href="/" className="pb-home-brand">{s.logo_url?<img src={s.logo_url} alt={s.website_name||'PinkBox'}/>:<span>PB</span>}<strong>{s.website_name||'PinkBox'}</strong></Link><nav>{nav.length?nav.slice(0,6).map((n,i)=><a key={i} href={n.url||n.href||'#products'}>{n.label||n.title||n.name}</a>):<><a href="#products">Shop</a><a href="#why-us">Why Us</a><a href="#reviews">Reviews</a><a href="#contact">Contact</a></>}</nav><div className="pb-home-tools">{s.phone&&<a className="pb-home-ghost" href={`tel:${s.phone}`} style={{padding:'8px 14px',marginRight:6}}><Phone size={14}/>{s.phone}</a>}<label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search"/></label><a href="/account" aria-label="Account">◯</a><a href="/wishlist" aria-label="Wishlist"><Heart size={19} fill={wish.length?'currentColor':'none'}/><i>{wish.length}</i></a><CartLink/></div></div></header>
 <section className="pb-home-hero"><div className="pb-home-hero-copy"><span className="pb-home-kicker">Soft. Safe. Rash-free.</span><h1>{pick(activeBanner?.title,'Comfort that stays with you, every single day')}</h1><p>{heroLine}</p><div className="pb-home-hero-actions"><a className="pb-home-primary" href={activeBanner?.button_url||'#products'}>{pick(activeBanner?.button_text,'Shop now')} <ArrowRight size={17}/></a><a className="pb-home-ghost" href="#why-us">Why choose us</a></div><div className="pb-home-proof"><span><BadgeCheck size={15}/>ISO certified unit</span><span><FlaskConical size={15}/>Lab tested quality</span><span><Boxes size={15}/>Bulk & retail supply</span></div></div><div className="pb-home-hero-art">{heroImage?<Image src={heroImage} alt={activeBanner?.title||shopProducts[0]?.title||'PinkBox product'} fill sizes="(max-width:1024px) 100vw, 55vw" style={{objectFit:'cover'}} priority/>:<div className="pb-art-fallback"><Sparkles/><b>PB</b></div>}<div className="pb-doodle pb-doodle-one">✦</div><div className="pb-doodle pb-doodle-two">◌</div><div className="pb-hero-note"><Star size={14} fill="currentColor"/><b>Made with care</b><small>Designed for everyday comfort</small></div><div className="pb-slider-nav">{banners.length>1&&<><button onClick={()=>setSlide(i=>(i-1+banners.length)%banners.length)} aria-label="Previous banner"><ArrowLeft size={16}/></button><span>{slide+1} / {banners.length}</span><button onClick={()=>setSlide(i=>(i+1)%banners.length)} aria-label="Next banner"><ArrowRight size={16}/></button></>}</div></div></section>
 <div className="pb-offer-strip"><div className="pb-offer-card"><b>10% off</b><span>Flat 10% off on your first order</span><code>WELCOME10</code></div><div className="pb-offer-card"><b>Free shipping</b><span>{freeShipLabel}</span></div><div className="pb-cert-row"><span><BadgeCheck size={15}/>ISO certified unit</span><span><FlaskConical size={15}/>Lab tested quality</span><span><ShieldCheck size={15}/>Discreet packaging</span><span><Boxes size={15}/>Bulk & retail supply</span>{s.cod_enabled&&<span><ShieldCheck size={15}/>COD available</span>}{s.online_payment_enabled&&<span><Phone size={15}/>UPI / online payment</span>}</div></div>
 <section className="pb-home-marquee"><div>{cats.slice(0,8).map((c,i)=><span key={c.id||i}>{c.name}<em>✦</em></span>)}</div></section>
 <section id="collections" className="pb-home-section pb-home-categories"><div className="pb-home-head"><div><span>SHOP BY CATEGORY</span><h2>A collection for every day</h2></div><a href="#products">View products <ArrowRight size={16}/></a></div>{cats.length?<div className="pb-category-grid">{cats.slice(0,6).map(c=><a key={c.id} href={`/collections/${c.slug}`} className="pb-category-card">{c.image_url?<Image src={c.image_url} alt={c.name||''} fill sizes="(max-width:768px) 50vw, 33vw" style={{objectFit:'cover'}}/>:<div className="pb-category-placeholder">{String(c.name||'P').slice(0,1)}</div>}<div><b>{c.name}</b><ArrowRight size={16}/></div></a>)}</div>:<div className="pb-home-empty">Publish categories from PinkBox Admin to fill this section.</div>}</section>
 <section id="products" className="pb-home-section pb-home-products"><div className="pb-home-head"><div><span>OUR RANGE</span><h2>{query?`Results for “${query}”`:'Pads for every day and every flow'}</h2></div><a href="/wishlist">Saved items <Heart size={15}/></a></div><div className="pb-product-grid">{shopProducts.map(p=><article key={p.id} className="pb-product-card"><a className="pb-product-image" href={`/products/${p.slug}`}>{p.image_url?<Image src={p.image_url} alt={p.title} fill sizes="(max-width:768px) 50vw, 25vw" style={{objectFit:'contain',padding:18}}/>:<b>PB</b>}{Number(p.compare_at_price)>0&&<em>SALE</em>}</a><button className="pb-heart" onClick={()=>toggle(p.id)} aria-label="Save to wishlist"><Heart size={17} fill={wish.includes(p.id)?'currentColor':'none'}/></button><div className="pb-product-info"><span>{p.brand||'PINKBOX'}</span><a href={`/products/${p.slug}`}><h3>{p.title}</h3></a><div><strong>{money(p.price)}</strong>{Number(p.compare_at_price)>0&&<del>{money(p.compare_at_price)}</del>}<a href={`/products/${p.slug}`} className="pb-view">View <ArrowRight size={14}/></a></div></div></article>)}</div>{!shopProducts.length&&<div className="pb-home-empty">No products found. Tell us what you want to sell and we will add it to the store.</div>}</section>
 <section id="story" className="pb-home-editorial"><div className="pb-editorial-art"><div className="pb-illustration"><div className="pb-illustration-circle"></div><div className="pb-illustration-card">PB</div><span>✿</span><span>◌</span><span>✦</span></div></div><div className="pb-editorial-copy"><span>OUR PROMISE</span><h2>Hygiene is not a luxury — it&apos;s a right.</h2><p>Premium everyday hygiene essentials, made for comfort, protection and confidence — with quality checked before dispatch.</p><ul className="pb-editorial-list"><li><BadgeCheck size={16}/>Made in an ISO-certified, hygienic facility</li><li><FlaskConical size={16}/>Lab-tested for quality and safety</li><li><ShieldCheck size={16}/>Options for every day, night and heavy use</li><li><Boxes size={16}/>Bulk supply for retailers, schools and NGOs</li></ul></div></section>
 {sections.slice(0,2).map((sec,i)=><section key={sec.id||i} className={`pb-home-custom ${i%2?'alt':''}`}><div><span>{String(sec.section_type||'FEATURE').replaceAll('_',' ')}</span><h2>{sec.title||sec.settings?.heading||'Designed around your everyday.'}</h2><p>{sec.settings?.description||sec.settings?.text||'A premium content block managed from PinkBox Admin.'}</p>{sec.settings?.button_text&&<a className="pb-home-primary" href={sec.settings?.button_url||'#products'}>{sec.settings.button_text}<ArrowRight size={17}/></a>}</div>{sec.settings?.image_url&&<img src={sec.settings.image_url} alt=""/>}</section>)}
 <section id="why-us" className="pb-home-section"><div className="pb-home-head"><div><span>WHY US</span><h2>Built on comfort, tested for safety</h2></div></div><div className="pb-home-benefits">{whyUs.map((b,i)=><div key={i}><b.icon/><b>{b.title}</b><small>{b.desc}</small></div>)}</div></section>
 {reviews.length>0&&<section id="reviews" className="pb-home-section"><div className="pb-home-head"><div><span>REAL VOICES</span><h2>Customer reviews</h2></div></div><div className="pb-review-grid">{reviews.map((r,i)=><div key={r.id||i} className="pb-review-card"><div className="pb-review-stars">{Array.from({length:5}).map((_,j)=><Star key={j} size={13} fill={j<(r.rating||5)?'currentColor':'none'}/>)}</div><p>{r.comment||r.review_text||''}</p><b>{r.customer_name||'Verified buyer'}</b></div>)}</div></section>}
 {blog.length>0&&<section id="journal" className="pb-home-section pb-home-journal"><div className="pb-home-head"><div><span>FROM THE JOURNAL</span><h2>Ideas, guides & updates</h2></div><Link href="/blog">View journal <ArrowRight size={16}/></Link></div><div className="pb-journal-grid">{blog.map(post=><a key={post.id} href={`/blog/${post.slug}`}>{post.cover_image_url?<div className="pb-journal-thumb"><Image src={post.cover_image_url} alt={post.title||''} fill sizes="(max-width:768px) 100vw, 33vw" style={{objectFit:'cover'}}/></div>:<div className="pb-journal-placeholder">PB</div>}<div><small>{post.published_at?new Date(post.published_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):''}</small><h3>{post.title}</h3><p>{post.excerpt||''}</p><span>Read story <ArrowRight size={14}/></span></div></a>)}</div></section>}
 <section className="pb-home-cta"><div><span>FIRST ORDER</span><h2>Get 10% off your first order</h2><p>Use <b>WELCOME10</b> at checkout. One clear offer, no confusion.</p></div><a className="pb-home-light" href="#products">Shop with WELCOME10 <ArrowRight size={17}/></a></section>
 <footer id="contact" className="pb-home-footer"><div className="pb-footer-brand"><Link href="/" className="pb-home-brand">{s.logo_url?<img src={s.logo_url} alt=""/>:<span>PB</span>}<strong>{s.website_name||'PinkBox'}</strong></Link><p>Comfort-focused sanitary care and everyday hygiene essentials, with discreet delivery across India.</p></div><div><b>Shop</b><a href="#products">All Products</a><a href="#products">New Arrivals</a><a href="#contact">Bulk Orders</a></div><div><b>Company</b><a href="#why-us">Why Us</a><a href="#reviews">Reviews</a><Link href="/blog">Journal</Link></div><div><b>Contact</b>{s.phone&&<span><Phone size={12}/>{s.phone}</span>}{s.email&&<span>{s.email}</span>}{s.address&&<span>{s.address}</span>}</div></footer>
 {whatsappUrl&&<a className="pb-whatsapp-float" href={whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label="Chat with PinkBox on WhatsApp"><span>WA</span><b>Chat on WhatsApp</b></a>}<div className="pb-home-bottom"><span>{data.footer?.copyright_text||`© ${new Date().getFullYear()} ${s.website_name||'PinkBox'}. All rights reserved.`}</span><span className="pb-legal-links"><Link href="/pages/about-us">About Us</Link><Link href="/pages/contact-us">Contact Us</Link><Link href="/pages/privacy-policy">Privacy Policy</Link><Link href="/pages/terms-conditions">Terms & Conditions</Link><Link href="/pages/refund-policy">Refund Policy</Link><Link href="/pages/shipping-policy">Shipping Policy</Link></span></div>
 </main>;
}
