'use client';
import {useEffect,useMemo,useState} from 'react';
import {Plus,Pencil,Trash2,RefreshCw,Search,X,Save,Upload,Image as ImageIcon,Star,AlertCircle,CheckCircle2} from 'lucide-react';
import {createClient} from '@/lib/supabase-browser';

const sb=createClient();
const TYPES=['image/jpeg','image/png','image/webp','image/gif'];
const fields=[
 ['sku','SKU','text',true],['title','Product Title','text',true],['slug','Slug','text'],['crm_product_id','CRM Product ID','text'],['brand','Brand','text'],
 ['short_description','Short Description','textarea'],['description','Description','textarea'],['price','Selling Price','number',true],['compare_at_price','Compare at Price','number'],['cost_price','Cost Price','number'],['gst_percent','GST %','number'],
 ['hsn_code','HSN Code','text'],['barcode','Barcode','text'],['weight','Weight','number'],['stock_quantity','Opening Stock','number'],['low_stock_threshold','Low Stock Alert','number'],
 ['track_inventory','Track Inventory','checkbox'],['allow_backorder','Allow Backorder','checkbox'],['featured','Featured','checkbox'],['is_active','Active','checkbox'],['seo_title','SEO Title','text'],['seo_description','SEO Description','textarea'],['seo_keywords','SEO Keywords','text']
];
const input='w-full rounded-lg border border-white/15 bg-[#151d30] px-3 py-2 text-xs text-white outline-none focus:border-pink-400 focus:ring-2 focus:ring-pink-400/15';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

function ProductForm({edit,form,setForm,onSave,saving,onClose,error,notice}){
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-3">
  <div className="flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-white/10 bg-[#10182a] shadow-2xl">
   <div className="flex shrink-0 items-center justify-between border-b border-white/10 px-4 py-3"><div className="text-sm font-semibold text-white">{edit?'Edit':'Add'} Product</div><button onClick={onClose} className="rounded-lg p-1 text-gray-300 hover:bg-white/10"><X size={18}/></button></div>
   {(error||notice)&&<div className={`mx-4 mt-3 flex items-center gap-2 rounded-lg border px-3 py-2 text-xs ${error?'border-red-400/30 bg-red-500/10 text-red-300':'border-emerald-400/30 bg-emerald-500/10 text-emerald-300'}`}>{error?<AlertCircle size={14}/>:<CheckCircle2 size={14}/>} {error||notice}</div>}
   <form onSubmit={onSave} className="grid gap-3 overflow-y-auto p-4 sm:grid-cols-2">
    {fields.map(([k,l,t,req])=><label key={k} className={t==='textarea'?'sm:col-span-2':''}><span className="mb-1 block text-[11px] font-semibold text-gray-200">{l}{req&&<b className="text-pink-400"> *</b>}</span>{t==='checkbox'?<span className="flex items-center gap-2 text-xs text-gray-200"><input type="checkbox" checked={!!form[k]} onChange={e=>setForm({...form,[k]:e.target.checked})}/>{l}</span>:t==='textarea'?<textarea rows={3} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})} className={input}/>:<input type={t} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})} className={input}/>}</label>)}
    <div className="sticky bottom-0 flex justify-end gap-2 border-t border-white/10 bg-[#10182a] pt-3 sm:col-span-2"><button type="button" onClick={onClose} className="rounded-lg border border-white/15 px-3 py-2 text-xs text-gray-200">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-pink-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50"><Save size={14}/>{saving?'Saving…':'Save Product'}</button></div>
   </form>
  </div>
 </div>
}

export default function WebsiteProductsManager(){
 const[products,setProducts]=useState([]),[images,setImages]=useState([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(false),[edit,setEdit]=useState(null),[form,setForm]=useState({}),[uploadingId,setUploadingId]=useState(''),[previewId,setPreviewId]=useState(''),[files,setFiles]=useState([]);
 const load=async()=>{setLoading(true);try{const [pr,im]=await Promise.all([fetch('/api/website/products',{cache:'no-store'}),fetch('/api/website/images',{cache:'no-store'})]);const pj=await pr.json(),ij=await im.json();if(!pr.ok)throw Error(pj.error||'Unable to load products');if(!im.ok)throw Error(ij.error||'Unable to load product images');setProducts(pj.data||[]);setImages(ij.data||[]);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const byProduct=useMemo(()=>{const m={};for(const img of images){(m[img.product_id]??=[]).push(img)}return m},[images]);
 const shown=useMemo(()=>products.filter(p=>JSON.stringify(p).toLowerCase().includes(q.toLowerCase())),[products,q]);
 const openEdit=p=>{const n={};fields.forEach(([k,,t])=>{let v=p?.[k];if(t==='checkbox')v=!!v;else if(v==null)v='';n[k]=v});setEdit(p);setForm(n);setError('');setNotice('');setModal(true)};
 const save=async e=>{e.preventDefault();setError('');setNotice('');for(const[k,l,t,req]of fields){if(req&&!String(form[k]??'').trim())return setError(`${l} is required.`);if(t==='number'&&form[k]!==''&&!Number.isFinite(Number(form[k])))return setError(`${l} must be a valid number.`)}setLoading(true);try{const p={...(edit||{}),...form};const r=await fetch('/api/website/products',{method:edit?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),j=await r.json();if(!r.ok)throw Error(j.error||'Save failed');setNotice(edit?'Product updated.':'Product created.');setModal(false);await load()}catch(e){setError(e.message)}finally{setLoading(false)}};
 const remove=async p=>{if(!confirm(`Delete ${p.title}?`))return;setError('');const r=await fetch(`/api/website/products?id=${p.id}`,{method:'DELETE'}),j=await r.json();if(!r.ok)setError(j.error||'Delete failed');else{setNotice('Product deleted.');load()}};
 const upload=async productId=>{if(!files.length)return setError('Select one or more images first.');setUploadingId(productId);setError('');setNotice('');try{const{data:{user}}=await sb.auth.getUser();if(!user)throw Error('Please sign in again.');const{data:profile,error:pe}=await sb.from('profiles').select('company_id').eq('id',user.id).maybeSingle();if(pe||!profile?.company_id)throw Error(pe?.message||'Company access unavailable.');const current=byProduct[productId]||[];for(let i=0;i<files.length;i++){const f=files[i];if(!TYPES.includes(f.type))throw Error(`${f.name}: unsupported image type.`);if(f.size>5*1024*1024)throw Error(`${f.name}: maximum size is 5 MB.`);const safe=f.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');const path=`${profile.company_id}/${productId}/${crypto.randomUUID()}-${safe}`;const{error:ue}=await sb.storage.from('product-images').upload(path,f,{contentType:f.type,upsert:false});if(ue)throw Error(ue.message);const{data:{publicUrl}}=sb.storage.from('product-images').getPublicUrl(path);const r=await fetch('/api/website/images',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:productId,image_url:publicUrl,alt_text:f.name.replace(/\.[^.]+$/,''),sort_order:current.length+i,is_primary:current.length===0&&i===0})});const j=await r.json();if(!r.ok)throw Error(j.error||'Image record save failed.')}setFiles([]);setPreviewId('');setNotice(`${files.length} image${files.length>1?'s':''} uploaded.`);await load()}catch(e){setError(e.message)}finally{setUploadingId('')}};
 const removeImage=async img=>{if(!confirm('Delete this image?'))return;const r=await fetch(`/api/website/images?id=${img.id}`,{method:'DELETE'}),j=await r.json();if(!r.ok)setError(j.error||'Delete failed');else{setNotice('Image deleted.');load()}};
 return <div className="space-y-4 text-white">
  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-lg font-semibold">Products</h1><p className="mt-1 text-[11px] text-gray-400">Product cards with integrated image upload, primary image and dimension-safe previews.</p></div><button onClick={()=>{setEdit(null);setForm({});setModal(true)}} className="inline-flex items-center justify-center gap-2 rounded-lg bg-pink-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14}/>Add Product</button></div>
  {(error||notice)&&<div className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-xs ${error?'border-red-400/30 bg-red-500/10 text-red-300':'border-emerald-400/30 bg-emerald-500/10 text-emerald-300'}`}>{error?<AlertCircle size={14}/>:<CheckCircle2 size={14}/>} {error||notice}</div>}
  <div className="flex gap-2"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products…" className="w-full rounded-lg border border-white/15 bg-[#151d30] py-2 pl-9 pr-3 text-xs text-white outline-none focus:border-pink-400"/></div><button onClick={load} className="rounded-lg border border-white/15 bg-[#151d30] px-3 text-gray-300"><RefreshCw size={15}/></button></div>
  {loading?<div className="rounded-xl border border-white/10 bg-[#11182b] p-10 text-center text-xs text-gray-400">Loading products…</div>:shown.length===0?<div className="rounded-xl border border-dashed border-white/15 bg-[#11182b] p-10 text-center text-xs text-gray-400">No products found.</div>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{shown.map(p=>{const imgs=byProduct[p.id]||[];const primary=imgs.find(x=>x.is_primary)||imgs[0];const isOpen=previewId===p.id;return <div key={p.id} className="overflow-hidden rounded-xl border border-white/10 bg-[#11182b] shadow-sm">
    <div className="relative flex aspect-[4/5] items-center justify-center overflow-hidden bg-[#f7f5f3]"><div className="absolute inset-0 flex items-center justify-center p-3">{primary?.image_url?<img src={primary.image_url} alt={p.title} className="h-full w-full object-contain"/>:<div className="text-4xl font-black text-gray-300">PB</div>}</div>{primary&&<span className="absolute left-2 top-2 rounded-full bg-pink-600 px-2 py-1 text-[9px] font-bold text-white">PRIMARY</span>}<button onClick={()=>{setPreviewId(isOpen?'':p.id);setFiles([])}} className="absolute right-2 top-2 rounded-lg bg-black/65 px-2 py-1 text-[9px] font-semibold text-white">{isOpen?'Close':'Images'} · {imgs.length}</button></div>
    {isOpen&&<div className="border-b border-white/10 bg-[#0e1628] p-3"><div className="mb-2 text-[10px] font-semibold text-gray-300">Upload product images</div><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))} className="block w-full text-[10px] text-gray-300"/><div className="mt-1 text-[9px] text-gray-500">JPG / PNG / WEBP / GIF · 5 MB each · original proportions preserved</div>{files.length>0&&<div className="mt-2 space-y-1 text-[9px] text-gray-400">{files.map(f=><div key={`${f.name}-${f.size}`} className="truncate">{f.name} · {(f.size/1024/1024).toFixed(2)} MB</div>)}</div>}<button onClick={()=>upload(p.id)} disabled={uploadingId===p.id} className="mt-2 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-pink-600 px-3 py-2 text-[10px] font-semibold text-white disabled:opacity-50"><Upload size={13}/>{uploadingId===p.id?'Uploading…':'Upload Images'}</button><div className="mt-3 grid grid-cols-4 gap-2">{imgs.map(img=><div key={img.id} className="overflow-hidden rounded-lg border border-white/10 bg-[#f7f5f3]"><div className="aspect-square"><img src={img.image_url} alt="" className="h-full w-full object-contain p-1"/></div><button onClick={()=>removeImage(img)} className="w-full border-t border-white/10 py-1 text-[8px] text-gray-300">Delete</button></div>)}</div></div>}
    <div className="space-y-2 p-3"><div><div className="truncate text-xs font-semibold text-white">{p.title}</div><div className="mt-0.5 text-[9px] text-gray-400">{p.sku||'No SKU'} {p.brand?`· ${p.brand}`:''}</div></div><div className="flex items-center justify-between"><span className="text-sm font-bold text-white">{money(p.price)}</span><span className={`text-[9px] font-semibold ${Number(p.stock_quantity||0)<=Number(p.low_stock_threshold||0)?'text-amber-300':'text-gray-400'}`}>Stock {p.stock_quantity||0}</span></div><div className="flex gap-2 pt-1"><button onClick={()=>openEdit(p)} className="inline-flex flex-1 items-center justify-center gap-1 rounded-lg border border-white/10 bg-white/5 px-2 py-1.5 text-[9px] text-gray-200"><Pencil size={12}/>Edit</button><button onClick={()=>remove(p)} className="inline-flex items-center justify-center rounded-lg border border-red-400/20 bg-red-500/10 px-2 text-[9px] text-red-300"><Trash2 size={12}/></button></div></div>
  </div>})}</div>}
  {modal&&<ProductForm edit={edit} form={form} setForm={setForm} onSave={save} saving={loading} onClose={()=>setModal(false)} error={error} notice={notice}/>} 
 </div>
}
