'use client';
import {useEffect,useState} from 'react';
import {RefreshCw,Save,PackageCheck,AlertTriangle,ShoppingBag,Users,IndianRupee,Boxes,Search,MessageCircle} from 'lucide-react';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
function Card({icon:Icon,label,value}){return <div className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3 text-gray-500"><Icon size={18}/><span className="text-sm">{label}</span></div><div className="mt-3 text-2xl font-semibold text-gray-900">{value}</div></div>}
export function WebsiteDashboard(){const[d,setD]=useState(null),[err,setErr]=useState('');const load=async()=>{try{const r=await fetch('/api/website/dashboard',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setD(j)}catch(e){setErr(e.message)}};useEffect(()=>{load()},[]);if(err)return <div className="rounded-xl bg-red-50 p-4 text-red-700">{err}</div>;if(!d)return <div className="p-12 text-center text-gray-500">Loading dashboard…</div>;
 const waNumber=String(d.whatsappNumber||'').replace(/[^0-9]/g,'');
 const summaryText=`📊 ${d.websiteName} — Today's Summary (${new Date().toLocaleDateString('en-IN')})\n\nOrders: ${d.today.orders} (COD: ${d.today.cod}, Online: ${d.today.online})\nSales: ${money(d.today.sales)}\n\nOverall — Total orders: ${d.stats.orders}, Total sales: ${money(d.stats.sales)}`;
 const lowStockText=d.lowStock.length?`⚠️ ${d.websiteName} — Low Stock Alert\n\n${d.lowStock.map(p=>`• ${p.title} (${p.sku||'—'}): ${p.stock_quantity||0} left`).join('\n')}`:'';
 const waHref=t=>waNumber?`https://wa.me/${waNumber}?text=${encodeURIComponent(t)}`:null;
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Website Dashboard</h1><p className="mt-1 text-sm text-gray-500">PinkBox online store overview.</p></div><button onClick={load} className="rounded-xl border bg-white p-2.5"><RefreshCw size={17}/></button></div>
 <div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm text-gray-500">Today · {new Date().toLocaleDateString('en-IN')}</div><div className="mt-1 flex flex-wrap items-baseline gap-x-6 gap-y-1"><span className="text-2xl font-semibold">{money(d.today.sales)}</span><span className="text-sm text-gray-500">{d.today.orders} orders · {d.today.cod} COD · {d.today.online} Online</span></div></div>{waHref(summaryText)&&<a href={waHref(summaryText)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#25D366] px-4 py-2.5 text-sm font-bold text-white"><MessageCircle size={16}/> Share summary</a>}</div></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={IndianRupee} label="Sales" value={money(d.stats.sales)}/><Card icon={ShoppingBag} label="Orders" value={d.stats.orders}/><Card icon={PackageCheck} label="Products" value={d.stats.products}/><Card icon={Users} label="Customers" value={d.stats.customers}/></div>
 <div className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border bg-white"><div className="border-b px-5 py-4 font-semibold">Recent Orders</div><div className="divide-y">{d.recentOrders.length?d.recentOrders.map(o=><div key={o.id} className="flex items-center justify-between px-5 py-4"><div><div className="font-medium">{o.order_number||o.id.slice(0,8)}</div><div className="text-xs text-gray-500">{new Date(o.created_at).toLocaleString('en-IN')}</div></div><div className="text-right"><div className="font-semibold">{money(o.total_amount)}</div><span className="text-xs uppercase text-gray-500">{o.order_status}</span></div></div>):<div className="p-8 text-center text-sm text-gray-500">No orders yet.</div>}</div></div>
 <div className="rounded-2xl border bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div className="flex items-center gap-2 font-semibold"><AlertTriangle size={17}/>Low Stock</div>{d.lowStock.length>0&&waHref(lowStockText)&&<a href={waHref(lowStockText)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 rounded-lg bg-[#25D366] px-3 py-1.5 text-xs font-bold text-white"><MessageCircle size={13}/> Share</a>}</div><div className="divide-y">{d.lowStock.length?d.lowStock.map(p=><div key={p.id} className="flex items-center justify-between px-5 py-4"><div><div className="font-medium">{p.title}</div><div className="text-xs text-gray-500">{p.sku}</div></div><div className="font-semibold text-amber-600">{p.stock_quantity||0}</div></div>):<div className="p-8 text-center text-sm text-gray-500">No low-stock products.</div>}</div></div></div></div>}
export function WebsiteSettings(){const[s,setS]=useState(null),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('');const load=async()=>{const r=await fetch('/api/website/settings',{cache:'no-store'}),j=await r.json();if(r.ok)setS(j.data);else setErr(j.error)};useEffect(()=>{load()},[]);const set=(k,v)=>setS(x=>({...x,[k]:v}));const save=async e=>{e.preventDefault();setSaving(true);setMsg('');setErr('');try{const r=await fetch('/api/website/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)}),j=await r.json();if(!r.ok)throw Error(j.error);setS(j.data);setMsg('Website settings saved.')}catch(e){setErr(e.message)}finally{setSaving(false)}};if(!s)return <div className="p-12 text-center text-gray-500">Loading settings…</div>;return <form onSubmit={save} className="space-y-5"><div><h1 className="text-2xl font-semibold">Website Settings</h1><p className="mt-1 text-sm text-gray-500">PinkBox storefront identity, contact, commerce and SEO defaults.</p></div>{(msg||err)&&<div className={`rounded-xl p-4 text-sm ${err?'bg-red-50 text-red-700':'bg-green-50 text-green-700'}`}>{err||msg}</div>}<div className="grid gap-5 lg:grid-cols-2">{[['website_name','Website Name'],['slug','Slug'],['logo_url','Logo URL'],['favicon_url','Favicon URL'],['whatsapp_number','WhatsApp Number'],['phone','Phone'],['email','Email'],['gstin','GSTIN'],['currency','Currency'],['timezone','Timezone'],['address','Business Address'],['meta_title','Meta Title'],['meta_description','Meta Description'],['free_shipping_threshold','Free Shipping Threshold'],['default_shipping_charge','Default Shipping Charge'],['ga4_measurement_id','Google Analytics 4 ID (G-XXXXXXX)'],['meta_pixel_id','Meta (Facebook) Pixel ID']].map(([k,l])=><label key={k} className={k==='address'||k==='meta_description'?'lg:col-span-2':''}><span className="mb-1.5 block text-sm font-medium">{l}</span>{k==='address'||k==='meta_description'?<textarea rows={3} value={s[k]??''} onChange={e=>set(k,e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/>:<input type={k.includes('threshold')||k.includes('charge')?'number':'text'} value={s[k]??''} onChange={e=>set(k,e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/>}</label>)}</div><div className="flex flex-wrap gap-5 rounded-2xl border bg-white p-5">{[['cod_enabled','Cash on Delivery'],['online_payment_enabled','Online Payment'],['shipping_enabled','Shipping']].map(([k,l])=><label key={k} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!s[k]} onChange={e=>set(k,e.target.checked)}/>{l}</label>)}</div><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-5 py-3 font-semibold text-white"><Save size={17}/>{saving?'Saving…':'Save Settings'}</button></form>}
export function WebsiteOrders(){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[err,setErr]=useState('');const load=async()=>{setLoading(true);const r=await fetch('/api/website/orders',{cache:'no-store'}),j=await r.json();if(r.ok)setRows(j.data||[]);else setErr(j.error);setLoading(false)};useEffect(()=>{load()},[]);const statuses=['new','confirmed','processing','packed','shipped','delivered','cancelled','returned','refunded'];const change=async(o,status)=>{const r=await fetch('/api/website/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:o.id,order_status:status,status_note:`Status changed to ${status}`})});const j=await r.json();if(!r.ok)setErr(j.error);else load()};return <div className="space-y-5"><div className="flex justify-between"><div><h1 className="text-2xl font-semibold">Orders</h1><p className="text-sm text-gray-500">Manage the complete order lifecycle.</p></div><button onClick={load} className="rounded-xl border bg-white p-2.5"><RefreshCw size={17}/></button></div>{err&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{err}</div>}<div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Order</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Date</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan="6" className="p-12 text-center">Loading…</td></tr>:rows.length===0?<tr><td colSpan="6" className="p-12 text-center text-gray-500">No orders yet.</td></tr>:rows.map(o=><tr key={o.id}><td className="px-4 py-3 font-medium">{o.order_number}</td><td className="px-4 py-3">{o.customer_name||'—'}<div className="text-xs text-gray-500">{o.phone||o.email||''}</div></td><td className="px-4 py-3">{money(o.total_amount)}</td><td className="px-4 py-3">{o.payment_method} / {o.payment_status}</td><td className="px-4 py-3"><select value={o.order_status} onChange={e=>change(o,e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs">{statuses.map(x=><option key={x}>{x}</option>)}</select></td><td className="px-4 py-3 text-gray-500">{new Date(o.created_at).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table></div></div></div>}
export function WebsiteInventory(){
 const[d,setD]=useState(null),[selected,setSelected]=useState(''),[change,setChange]=useState(''),[reason,setReason]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[filter,setFilter]=useState('all');
 const load=async()=>{try{setErr('');const r=await fetch('/api/website/inventory',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load inventory');setD(j)}catch(e){setErr(e.message)}};
 useEffect(()=>{load()},[]);
 const adjust=async e=>{e.preventDefault();setBusy(true);setMsg('');setErr('');try{const r=await fetch('/api/website/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:selected,change_quantity:Number(change),reason})}),j=await r.json();if(!r.ok)throw Error(j.error||'Stock adjustment failed');setMsg('Stock adjusted successfully.');setSelected('');setChange('');setReason('');await load()}catch(e){setErr(e.message)}finally{setBusy(false)}};
 if(!d)return <div className="p-12 text-center text-gray-500">{err||'Loading inventory…'}</div>;
 const products=d.products||[];
 const lowCount=products.filter(p=>Number(p.stock_quantity)>0&&Number(p.stock_quantity)<=Number(p.low_stock_threshold)).length;
 const outCount=products.filter(p=>Number(p.stock_quantity)<=0).length;
 const visible=products.filter(p=>{const matches=JSON.stringify(p).toLowerCase().includes(q.toLowerCase());const stock=Number(p.stock_quantity||0);return matches&&(filter==='all'||(filter==='low'&&stock>0&&stock<=Number(p.low_stock_threshold||0))||(filter==='out'&&stock<=0))});
 const productName=id=>products.find(p=>p.id===id)?.title||'Unknown product';
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Inventory</h1><p className="text-sm text-gray-500">Stock overview, atomic adjustments and transaction history.</p></div><button onClick={load} disabled={busy} className="rounded-xl border bg-white p-2.5" aria-label="Refresh inventory"><RefreshCw size={17}/></button></div>
  {(msg||err)&&<div className={err?'rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700':'rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-700'}>{err||msg}</div>}
  <div className="grid gap-4 sm:grid-cols-3">
   <button onClick={()=>setFilter('all')} className={filter==='all'?'rounded-2xl border bg-white p-5 text-left ring-2 ring-gray-900':'rounded-2xl border bg-white p-5 text-left'}><div className="text-sm text-gray-500">Tracked products</div><div className="mt-2 text-2xl font-semibold">{products.length}</div></button>
   <button onClick={()=>setFilter('low')} className={filter==='low'?'rounded-2xl border bg-white p-5 text-left ring-2 ring-gray-900':'rounded-2xl border bg-white p-5 text-left'}><div className="text-sm text-gray-500">Low stock</div><div className="mt-2 text-2xl font-semibold text-amber-600">{lowCount}</div></button>
   <button onClick={()=>setFilter('out')} className={filter==='out'?'rounded-2xl border bg-white p-5 text-left ring-2 ring-gray-900':'rounded-2xl border bg-white p-5 text-left'}><div className="text-sm text-gray-500">Out of stock</div><div className="mt-2 text-2xl font-semibold text-red-600">{outCount}</div></button>
  </div>
  <div className="grid gap-5 lg:grid-cols-[1fr_360px]">
   <div className="rounded-2xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div className="font-semibold">Stock Overview</div><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search product or SKU" className="rounded-xl border py-2 pl-9 pr-3 text-sm"/></div></div><div className="divide-y">{visible.length?visible.map(p=><div key={p.id} className="flex items-center justify-between px-5 py-4"><div><div className="font-medium">{p.title}</div><div className="text-xs text-gray-500">{p.sku||'No SKU'}</div></div><div className="text-right"><div className={Number(p.stock_quantity)<=0?'font-semibold text-red-600':Number(p.stock_quantity)<=Number(p.low_stock_threshold)?'font-semibold text-amber-600':'font-semibold text-gray-900'}>{p.stock_quantity||0}</div><div className="text-xs text-gray-400">alert {p.low_stock_threshold||0}</div></div></div>):<div className="p-10 text-center text-sm text-gray-500">No matching products.</div>}</div></div>
   <form onSubmit={adjust} className="h-fit rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center gap-2 font-semibold"><Boxes size={18}/>Stock Adjustment</div><select required value={selected} onChange={e=>setSelected(e.target.value)} className="mb-3 w-full rounded-xl border px-3 py-2.5"><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.title} ({p.sku})</option>)}</select><input required type="number" step="any" value={change} onChange={e=>setChange(e.target.value)} placeholder="+10 or -5" className="mb-3 w-full rounded-xl border px-3 py-2.5"/><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason (e.g. received stock, damaged, correction)" rows="3" className="mb-3 w-full rounded-xl border px-3 py-2.5"/><button disabled={busy} className="w-full rounded-xl bg-gray-900 py-2.5 font-semibold text-white disabled:opacity-50">{busy?'Updating…':'Adjust Stock'}</button></form>
  </div>
  <div className="rounded-2xl border bg-white"><div className="border-b px-5 py-4 font-semibold">Recent Stock Transactions</div><div className="divide-y">{d.transactions.length?d.transactions.map(t=><div key={t.id} className="flex items-center justify-between gap-4 px-5 py-3 text-sm"><div><div className="font-medium">{productName(t.product_id)}</div><div className="text-xs text-gray-500">{t.reason||'Adjustment'} · {new Date(t.created_at).toLocaleString('en-IN')}</div></div><div className="text-right"><div className={Number(t.change_quantity)>0?'font-semibold text-green-600':'font-semibold text-red-600'}>{Number(t.change_quantity)>0?'+':''}{t.change_quantity}</div><div className="text-xs text-gray-500">after {t.quantity_after}</div></div></div>):<div className="p-8 text-center text-gray-500">No transactions.</div>}</div></div>
 </div>
}export function WebsiteCustomers(){const[r,setR]=useState([]),[q,setQ]=useState('');useEffect(()=>{fetch('/api/website/customers',{cache:'no-store'}).then(x=>x.json()).then(j=>setR(j.data||[]))},[]);const a=(r||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">Customers</h1><p className="text-sm text-gray-500">Live customer master from BK CRM. Website orders link back to this master.</p></div><div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers..." className="w-full rounded-xl border bg-white py-2.5 pl-10 pr-3"/></div><div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Firm</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">GSTIN</th></tr></thead><tbody className="divide-y">{a.map(x=><tr key={x.id}><td className="px-4 py-3 font-medium">{[x.client_name,x.surname].filter(Boolean).join(' ')||'—'}</td><td className="px-4 py-3">{x.firm_name||'—'}</td><td className="px-4 py-3">{x.phone1||x.phone2||'—'}</td><td className="px-4 py-3">{x.email||'—'}</td><td className="px-4 py-3">{[x.city,x.state,x.pincode].filter(Boolean).join(', ')||'—'}</td><td className="px-4 py-3">{x.gstin||'—'}</td></tr>)}</tbody></table></div></div>}
