import { createAdminClient } from '@/lib/supabase-admin';

async function getStore(){const db=createAdminClient();const {data:settings}=await db.from('website_settings').select('*').eq('slug','24care').eq('status','active').maybeSingle();return{db,settings};}
export async function GET(){const{db,settings}=await getStore();if(!settings)return Response.json({error:'Store is not configured.'},{status:404});const c=settings.company_id;const now=new Date().toISOString();const[products,categories,banners,sections,pages,menu,theme,footer,blog]=await Promise.all([
 db.from('website_products').select('id,sku,title,slug,short_description,description,brand,price,compare_at_price,gst_percent,stock_quantity,featured,is_active,seo_title,seo_description').eq('company_id',c).eq('is_active',true).order('created_at',{ascending:false}),
 db.from('website_categories').select('id,name,slug,parent_id,image_url,sort_order').eq('company_id',c).eq('is_active',true).order('sort_order'),
 db.from('website_banners').select('id,title,subtitle,image_url,mobile_image_url,button_text,button_url,sort_order,starts_at,ends_at').eq('company_id',c).eq('is_active',true).order('sort_order'),
 db.from('website_homepage_sections').select('id,section_type,title,settings,sort_order').eq('company_id',c).eq('is_active',true).order('sort_order'),
 db.from('website_pages').select('id,title,slug,content,seo_title,seo_description').eq('company_id',c).eq('is_published',true).order('title'),
 db.from('website_menus').select('location,name,items').eq('company_id',c).eq('location','header').maybeSingle(),
 db.from('website_theme_settings').select('*').eq('company_id',c).maybeSingle(),
 db.from('website_footer_settings').select('*').eq('company_id',c).maybeSingle(),
 db.from('website_blog_posts').select('id,title,slug,excerpt,content,featured_image_url,author_name,category,tags,seo_title,seo_description,published_at').eq('company_id',c).eq('status','published').lte('published_at',now).order('published_at',{ascending:false}).limit(20)
]);
 const activeBanners=(banners.data||[]).filter(x=>(!x.starts_at||x.starts_at<=now)&&(!x.ends_at||x.ends_at>=now));
 return Response.json({settings:{website_name:settings.website_name,slug:settings.slug,logo_url:settings.logo_url,whatsapp_number:settings.whatsapp_number,phone:settings.phone,email:settings.email,address:settings.address,currency:settings.currency,cod_enabled:settings.cod_enabled,online_payment_enabled:settings.online_payment_enabled,shipping_enabled:settings.shipping_enabled,free_shipping_threshold:settings.free_shipping_threshold,default_shipping_charge:settings.default_shipping_charge,meta_title:settings.meta_title,meta_description:settings.meta_description},products:products.data||[],categories:categories.data||[],banners:activeBanners,sections:sections.data||[],pages:pages.data||[],menu:menu.data||null,theme:theme.data||null,footer:footer.data||null,blog:blog.data||[]});}
export async function POST(request){const{db,settings}=await getStore();if(!settings)return Response.json({error:'Store is not configured.'},{status:404});const b=await request.json().catch(()=>null);if(!b)return Response.json({error:'Invalid JSON.'},{status:400});const c=settings.company_id;
 if(b.action==='abandoned_cart'){if(!b.session_id)return Response.json({error:'session_id is required.'},{status:400});const payload={company_id:c,session_id:String(b.session_id).slice(0,200),customer_name:String(b.name||'').trim()||null,phone:String(b.phone||'').trim()||null,email:String(b.email||'').trim()||null,items:Array.isArray(b.items)?b.items:[],subtotal:Number(b.subtotal||0),status:'abandoned',last_activity_at:new Date().toISOString(),updated_at:new Date().toISOString()};const{data,error}=await db.from('website_abandoned_carts').upsert(payload,{onConflict:'company_id,session_id'}).select('id,status').single();if(error)return Response.json({error:error.message},{status:500});return Response.json({data});}
 if(!b.name||!b.phone||!b.address||!Array.isArray(b.items)||!b.items.length)return Response.json({error:'Name, phone, address and at least one product are required.'},{status:400});
 const address={name:String(b.name).trim(),phone:String(b.phone).trim(),email:String(b.email||'').trim()||null,address:String(b.address).trim(),pincode:String(b.pincode||'').trim(),city:String(b.city||'').trim(),state:String(b.state||'').trim()};
 const{data,error}=await db.rpc('place_website_order',{p_company_id:c,p_name:address.name,p_phone:address.phone,p_email:address.email,p_address:address,p_items:b.items,p_payment_method:b.payment_method==='online'?'ONLINE':'COD',p_note:String(b.note||'').trim()||null,p_coupon_code:String(b.coupon_code||'').trim()||null});if(error)return Response.json({error:error.message.replace(/^.*ERROR:\s*/,'')},{status:400});
 if(data?.order_id)await db.from('website_abandoned_carts').update({status:'recovered',recovered_order_id:data.order_id,updated_at:new Date().toISOString()}).eq('company_id',c).eq('session_id',String(b.session_id||''));return Response.json(data,{status:201});}
